 /******************************************************************
 *
 *     Copyright (c) 2003-2023 Volkswagen AG, D-38436 Wolfsburg
 *
 ******************************************************************
 *
 * Projekt:    BAP (P0674)
 * Komponente: Konfiguration
 *
 ******************************************************************
 *
 * Beschreibung
 *
 *  Diese Datei enthaelt alle #defines zur Anpassung der BAP-SSW
 *  an den jeweiligen Steuergeraetetyp. Mit Hilfe von Makro-Schaltern
 *  werden einzelne Funktionalitaeten an- bzw. ausgeschaltet. Damit
 *  wird die SW optimal an die zur Verfuegung stehenden Ressourcen
 *  angepasst.
 *
 ******************************************************************
 * Generiert am:    10.08.2026
 *           um:    09:46:27
 * Quelldatei:      C:\workspace\docs\8255_antona_1000\BAP\BAP_v1.12.2_Distribution_2023-10-10\Distribution\POC_8255\input\BAP_SW1.12_ICC_MQBevo_V2_187.xml
 * Zieldatei:       C:\workspace\docs\8255_antona_1000\BAP\BAP_v1.12.2_Distribution_2023-10-10\Distribution\POC_8255\output\bap_defines.h
 *
 * BAPgen Version:  1.12.2
 * BAPgen Stand:    10.10.2023
 ******************************************************************/

#ifndef BAP_DEFINES_H
#define BAP_DEFINES_H

#ifdef __cplusplus
extern "C" {
#endif

/* Makro-Definitionen */

/**
 * Makro bei der Verwendung des erweiterten Adressierungsbereiches
 */
#define BAP_USES_EXCLUSIVE_ADDRESS 

/**
 * Makro bei der Verwendung der Ethernet-Kommunikation
 */
#define BAP_USES_ETH

/**
 * Type Definition des Steuergeraetes
 */
#define BAP_SGTYPE_IS_ASG_AND_LARGE_FSG

/**
 * XML-Versionsinfo MAJOR. Ergibt mit der BAP_XML_VERSION_MINOR zusammen die Version.
 */
#define BAP_XML_VERSION_MAJOR 2

/**
 * XML-Versionsinfo MINOR. Ergibt mit der BAP_XML_VERSION_MAJOR zusammen die Version
 */
#define BAP_XML_VERSION_MINOR 187

/**
 * Name der XML-Datei aus der die Konfiguration stammt.
 */
#define BAP_SSW_XML (BAP_SW1.12_ICC_MQBevo_V2_187.xml)

/**
 * Anzahl der Zeilen in der BAP_CanTxRomTable
 */
#define BAP_CAN_TX_ROM_TABLE_ROWS ((uint16_t)1670)

/**
 * Anzahl der Zeilen in der BAP_CanRxRomTable
 */
#define BAP_CAN_RX_ROM_TABLE_ROWS ((uint16_t)1820)

/**
 * Maximale PDU-Groesse der verarbeiteten Config-XML.
 * Wird automatisch auf 8 gesetzt, sofern kein Eintrag vorhanden oder kleiner 8.
 */
#define BAP_MAX_PDU_SIZE ((uint16_t)1444)

/**
 * Anzahl der Zeilen in der BAP_InhibitRamTable
 */
#define BAP_INHIBIT_ROWS ((uint16_t)67)

/**
 * Haelt die Anzahl an Zyklen, die nach eine segmentierte Botschaft zusaetzlich warten muss.
 * Siehe Tag <InhibitAdditional> in Config-XML.
 */
#define BAP_INHIBITADDITIONAL_TIMER ((uint8_t)1)

/**
 * Anzahl der Zeilen in BAP_CanTxSegmentationChannels
 */
#define BAP_CAN_TX_SEGMENTATION_CHANNELS ((uint16_t)67)

/**
 * Anzahl der Zeilen in BAP_CanRxSegmentationChannels
 */
#define BAP_CAN_RX_SEGMENTATION_CHANNELS ((uint16_t)75)

/**
 * Enthaelt die Anzahl der Bytes von BAP_CanRxRingBuffer.
 */
#define BAP_CAN_RX_RING_BUFFER_SIZE ((uint32_t)38746)

/**
 * Anzahl der Zeilen in der BAP_u16InterTelegramTimerTable
 */
#define BAP_INTER_TELEGRAM_TIMER_ROWS ((uint16_t)431)

/**
 *  Haelt die Anzahl an Zeilen, die die Tabelle BAP_LsgRomTables enthaelt.
 */
#define BAP_LSG_ROM_TABLE_ROWS ((uint8_t)63)

/**
 *  Haelt die Anzahl an Zeilen, die die Tabelle BAP_pLsgRomTable enthaelt.
 */
#define BAP_P_LSG_ROM_TABLE_ROWS ((uint8_t)63)

/**
 * Enthaelt die Anzahl der Elemente von BAP_FctRomTable.
 */
#define BAP_FCT_ROM_TABLE_ROWS ((uint16_t)1670)

/**
 * Enthaelt die Anzahl der Elemente von BAP_BAPConfigTable.
 */
#define BAP_BAPCONFIG_TABLE_ROWS ((uint8_t)63)

/**
 * Haelt die Anzahl an Zeilen, die die Tabelle BAP_MapCanIdToLsgRomRowTable enthaelt.
 */
#define BAP_MAP_CANID_TO_LSGROMROW_TABLE_ROWS ((uint16_t)67)

/**
 * Haelt die Anzahl an Zeilen, die die Tabelle BAP_CanRxMsgToLsgMappingTable enthaelt.
 */
#define BAP_CAN2LSGID_TABLE_ROWS ((uint8_t)26)

/**
 * Enthaelt die hoechste in der Konfiguration verwendete LsgId.
 */
#define BAP_IDX_HIGHEST_LSG ((uint8_t)133)

/**
 *  Diese Auflistung enthaelt alle Fehlercodes von BAP.
 *  Diese werden als Rueckgabewert bei Funktionsaufrufen zurueckgegeben
 */
 typedef enum BapError_t
 {
     /**
     * Der Funktionsaufruf war erfolgreich.
     */
     BapErr_OK = 0x00,

     /* BCL Fehlermeldungen */
     /**
     * Sequenzbotschaft ohne vorangegangene Startbotschaft empfangen
     * @remarks
     * Dieser Fehlercode tritt ab BAP 1.4 nur dann auf, wenn nach dem Ausloesen
     * des Fehlers BapErr_TimeoutSegmentation noch Sequenzbotschaften folgen.
     *
     * In Vorgaengerversionen trat der Fehler immer auf, wenn eine Sequenzbotschaft
     * ohne Startbotschaft empfangen wurde.
     *
     * Grund fuer die Aenderung: Die dynamische Kanalvergabe erlaubt es, dass eine
     * CAN-Id/Segmentierungskanal nun mehrere LSGs adressieren kann, welche auf 
     * unterschiedlichen physikalischen Steuergeraeten realisiert sein koennen.
     *
     * Ein Aussenden einer segmentierten Botschaft haette zur Folge gehabt, dass
     * im jeweils gerade nicht adressierten Steuergeraet sehr viele Fehlermeldungen 
     * ausgeloest worden waeren.
     */
     BapErr_IllegalSequence = 0x12,

     /**
     * Nicht erwartete Sequenznummer empfangen.
     */
     BapErr_SequenceNumber = 0x13,

     /**
     * Folgebotschaft nicht rechtzeitig empfangen.
     * Die Intertelegrammzeit wurde verletzt.
     */
     BapErr_TimeoutSegmentation = 0x14,

     /**
     * Datenelement passt nicht in BCL Rx Puffer
     */
     BapErr_OversizeSegmentation  = 0x15,

     /**
     * Beim Datenempfang wurden weniger Datenbytes empfangen, als erforderlich gewesen waeren.
     *
     * @example
     * Im ASG ist Funktion 17 als Int16 definiert.
     * Im FSG ist Funktion 17 als Int8 definiert.
     * Es erfolgt eine Datenuebertragung mit eingeschaltetem variablen DLC ueber CAN.
     * Das ASG erhaelt also 3 Bytes (2 Byte Header + 1 Byte Nutzdaten).
     * Da 1 Byte Nutzdaten nicht ausreichen, um einen 16 Bit Wert zu fuellen wird die
     * Nachricht verworfen und dieser Fehler gemeldet.
     */
     BapErr_BadDataLength = 0x16,

     /**
     * Pufferueberlauf beim Empfang von Daten.
     * Bei korrekter Konfiguration der Ringpuffergroesse darf dieser Fehler nicht auftreten.
     */
     BapErr_ReceivedDataLost = 0x17,
     
     /* BPL Fehlermeldungen */
     /**
     * ASG Zeitueberwachungen Heartbeat - Cache wurde ungueltig gesetzt
     */
     BapErr_TimeoutHeartbeat = 0x21,

     /**
     * Alle Retrys waren erfolglos.
     */
     BapErr_RetryNotSuccessful = 0x22,

     /**
      * Die Processing Nachricht vom FSG kam nicht rechtzeitig im ASG an
      * Wird von der gleichen Funktionalitaet im BPL ausgeloest wie BapErr_RetryNotSuccessful
      */
     BapErr_ProcessingTimeout = 0x38,

     /**
     * Der Vorgang wurde nicht ausgefuehrt, weil zuviele interne Vorgaenge anstehen.
     * Genauere Beschreibung bei den Rueckgabewerten der einzelnen Funktionen.
     */
     BapErr_Busy = 0x23,

     /**
     * Die max. zu erwartende Antwortzeit wurde ueberschritten, ohne dass der Request
     * abgesendet werden konnte.
     *
     * @remarks Dieser Fehler kann auch bei unsegmentierten Nachrichten auftreten.
     * @remarks Der Fehler tritt nur im ASG auf.
     */
     BapErr_RequestTimeout = 0x24,


     /* BAL Fehlermeldungen */
     /**
     * Die Protokollversion des FSG passt nicht mit der des ASG zusammen.
     */
     BapErr_IncompatibleProtocolVersion = 0x32,

     /**
     * Die Datenfestlegung des FSG passt nicht mit der des ASG zusammen.
     */
     BapErr_IncompatibleDataSpecification = 0x33,

     /**
     * Die Daten im Cache sind ungueltig.
     * @remarks: 
     * Tritt nur im ASG als synchroner Fehler auf.
     */
     BapErr_CacheInvalid = 0x34,

     /**
     * Die Daten im Cache sind ungueltig.
     * @remarks: 
     * Tritt nur im ASG als asynchroner Fehler auf.
     */
     BapErr_GetAllMessageCorrupted = 0x39,

     /**
     * Mindestens ein Sendepuffer wurde nicht initialisiert.
     * @remarks:
     * Tritt nur im FSG als synchroner Fehler auf.
     */
     BapErr_SendBufferNotInitialized = 0x3A,

     /**
     * Diese Operation ist in diesem Zustand nicht erlaubt.
     * @remarks
     * Dieser Fehler tritt haeufig auf, wenn BAP_Init oder BAP_Start nicht aufgerufen wurden
     * oder danach BAP_Shutdown aufgerufen wurde.
     * Im ASG schlagen alle Request-Aufrufe fehl, solange keine BAP_Config empfangen wurde.
     */
     BapErr_InvalidState = 0x35,

     /**
     * Fuer den geforderten Cache Zugriff der angegebene FunktionId gibt es kein Cache.
     */
     BapErr_CacheNotAvailable = 0x36,

     /**
     * Einer der uebergebenen Parameter ist ungueltig.
     * (Null-Zeiger, ungueltige FctId oder LsgId, Requesttyp fuer diese Funktionsklasse nicht
     * erlaubt, Datentyp der Funktion und FunktionID stimmen nicht ueberein)
     */
     BapErr_InvalidArg = 0x37,

     /*
     * If a call to BAP_SendDebugInfo() is done and the global active flag is disabling the send of debug info
     * it will return BapErr_SendDebugDisable.
     */
     BapErr_SendDebugDisable = 0x51
,
    AppErr_OutOfRange = 0x41,
    AppErr_TemporaryNotAvailable = 0x42,
    AppErr_MaxDatalengthExceeded = 0x43,
    AppErr_UnitMismatch = 0x44,
    AppErr_Parameter_Mismatch = 0x45,
    AppErr_InvalidArgument = 0x46,
    AppErr_FailedToCreateNewListMember = 0x47,
    AppErr_MethodAborted = 0x50,
    AppErr_Unknown = 0x80,
    AppErr_DataInvalid = 0x83,
    AppErr_NoNetwork = 0x89,
    AppErr_NotRegistered_EmergencyCallOnly = 0x8B,
    AppErr_NoRedialnumber = 0x8F,
    AppErr_ActiveCallPresent_Dialing = 0x90,
    AppErr_HeldCallPresent = 0x91,
    AppErr_NoCall = 0x93,
    AppErr_NoCallRelatedToCallID = 0x94,
    AppErr_NoActiveCall = 0x95,
    AppErr_NoCallOnHold = 0x96,
    AppErr_NoIncomingCall = 0x97,
    AppErr_NoConference = 0x9A,
    AppErr_NoMemberOfConference = 0x9B,
    AppErr_MaximumNumberForMembersOfConferenceReached = 0x9C,
    AppErr_NotSupportedByMobilePhone_HFP = 0xA0,
    AppErr_NoHeadsetConnected = 0xA1,
    AppErr_NoPairedHeadset = 0xA2
}BapError_et;

#ifdef BAP_NOT_USES_NAMED_IDS
/** Der Datentyp fuer die Kennung eines Logischen Steuer-Geraetes */
typedef uint8_t lsgId_t;
/** Der Datentyp fuer die Kennung einer Funktion eines Logischen Steuer-Geraetes */
typedef uint8_t fctId_t;

#else
/**
 * Symbolische Namen fuer LSGs und Funktionen werden verwendet.
 */
#define BAP_USES_NAMED_IDS

/**
 * Benamte Bezeichner fuer logische Steuergeraete
 */
typedef enum BapLsg_t
{
  BapLsg_Reserved = 0x00,
  BapLsg_ClimateZone = 0x01,
  BapLsg_ClimateZone2 = 0x02,
  BapLsg_ParkHeater = 0x03,
  BapLsg_HeadUpDisplay = 0x04,
  BapLsg_ACC = 0x05,
  BapLsg_RDK = 0x07,
  BapLsg_InteriorLight = 0x08,
  BapLsg_ExteriorLight = 0x09,
  BapLsg_PDC = 0x0a,
  BapLsg_VPS = 0x0b,
  BapLsg_Wiper_Comfort = 0x0c,
  BapLsg_Doorlocking = 0x0d,
  BapLsg_Mirror = 0x0e,
  BapLsg_BC_MFA = 0x0f,
  BapLsg_Seat = 0x10,
  BapLsg_Clock = 0x11,
  BapLsg_SIA = 0x12,
  BapLsg_UnitMaster = 0x13,
  BapLsg_HomeLink = 0x14,
  BapLsg_Charisma = 0x17,
  BapLsg_LDW_HCA = 0x19,
  BapLsg_SWA = 0x1a,
  BapLsg_AWV = 0x1b,
  BapLsg_Hybrid = 0x1d,
  BapLsg_SeatBF = 0x20,
  BapLsg_VZA = 0x21,
  BapLsg_MKE = 0x22,
  BapLsg_BCmE = 0x23,
  BapLsg_BatteryControl = 0x25,
  BapLsg_Brake = 0x26,
  BapLsg_Telephone = 0x28,
  BapLsg_OnlineFunctions_SD = 0x2a,
  BapLsg_Audio_SD = 0x31,
  BapLsg_Navigation_SD = 0x32,
  BapLsg_eCall = 0x33,
  BapLsg_MFL_Config = 0x34,
  BapLsg_TrailerAssist = 0x36,
  BapLsg_ENI = 0x37,
  BapLsg_RangeData = 0x39,
  BapLsg_SeatPneumatic = 0x3b,
  BapLsg_EfficiencyAssist = 0x3c,
  BapLsg_ClimateMaster = 0x42,
  BapLsg_DisplayConfig = 0x45,
  BapLsg_SDS_SD = 0x46,
  BapLsg_Statistics = 0x4a,
  BapLsg_Sunroof = 0x4b,
  BapLsg_FAS_Profiles = 0x4d,
  BapLsg_InfoSettings = 0x50,
  BapLsg_PaCo = 0x55,
  BapLsg_ENI2 = 0x58,
  BapLsg_EngineFunctions = 0x5d,
  BapLsg_TPA = 0x5f,
  BapLsg_Car2X = 0x61,
  BapLsg_IAA_PSO2 = 0x74,
  BapLsg_RollingAbility = 0x75,
  BapLsg_BSMOIS = 0x76,
  BapLsg_MobDevKey = 0x77,
  BapLsg_BSMOIS2 = 0x7a,
  BapLsg_BSMOIS3 = 0x7b,
  BapLsg_RushhourPilot = 0x7c,
  BapLsg_PlugAndCharge = 0x80,
  BapLsg_California = 0x81,
  BapLsg_SLCView = 0x85
}lsgId_t;

/**
 * Benamte Bezeichner fuer die Funktionen der verschiedenen logischen Steuergeraete
 */
typedef enum BapFct_t
{
  BapFct_Reserved = 0x00,
  /* Steuergeraet ClimateZone */
  BapFct_ClimateZone_GetAll = 0x01,
  BapFct_ClimateZone_BAP_Config = 0x02,
  BapFct_ClimateZone_FunctionList = 0x03,
  BapFct_ClimateZone_HeartBeat = 0x04,
  BapFct_ClimateZone_FSG_Control = 0x0d,
  BapFct_ClimateZone_FSG_Setup = 0x0e,
  BapFct_ClimateZone_FSG_OperationState = 0x0f,
  BapFct_ClimateZone_ZL_Temperature = 0x10,
  BapFct_ClimateZone_ZR_Temperature = 0x11,
  BapFct_ClimateZone_ZL_AirVolume = 0x12,
  BapFct_ClimateZone_ZR_AirVolume = 0x13,
  BapFct_ClimateZone_ZL_AirDistribution = 0x14,
  BapFct_ClimateZone_ZR_AirDistribution = 0x15,
  BapFct_ClimateZone_ZL_SeatClimate = 0x16,
  BapFct_ClimateZone_ZR_SeatClimate = 0x17,
  BapFct_ClimateZone_ZL_FootwellTemperature = 0x18,
  BapFct_ClimateZone_ZR_FootwellTemperature = 0x19,
  BapFct_ClimateZone_ZL_ClimateStyle = 0x1a,
  BapFct_ClimateZone_ZR_ClimateStyle = 0x1b,
  BapFct_ClimateZone_ZL_ClimateState = 0x1c,
  BapFct_ClimateZone_ZR_ClimateState = 0x1d,
  BapFct_ClimateZone_ZL_IndividualClimatisation = 0x1e,
  BapFct_ClimateZone_ZR_IndividualClimatisation = 0x1f,
  BapFct_ClimateZone_ZL_Ionisator = 0x20,
  BapFct_ClimateZone_ZR_Ionisator = 0x21,
  BapFct_ClimateZone_ZL_BodyCloseMeasures = 0x22,
  BapFct_ClimateZone_ZR_BodyCloseMeasures = 0x23,
  BapFct_ClimateZone_NozzlePositioning = 0x24,
  BapFct_ClimateZone_NozzleControl = 0x25,
  BapFct_ClimateZone_NozzleStatus = 0x26,
  BapFct_ClimateZone_ZL_AUTO = 0x27,
  BapFct_ClimateZone_ZR_AUTO = 0x28,
  BapFct_ClimateZone_FootHeater = 0x29,
  BapFct_ClimateZone_FSG_Setup2 = 0x2a,
  BapFct_ClimateZone_ZL_IntelligentAUTO = 0x2b,
  BapFct_ClimateZone_ZR_IntelligentAUTO = 0x2c,
  BapFct_ClimateZone_AirDistributionPresetList = 0x2d,
  BapFct_ClimateZone_ZL_AdaptSeatClimateCtrl = 0x2e,
  BapFct_ClimateZone_ZR_AdaptSeatClimateCtrl = 0x2f,
  BapFct_ClimateZone_ZL_AutomaticSeatClimate = 0x30,
  BapFct_ClimateZone_ZR_AutomaticSeatClimate = 0x31,
  BapFct_ClimateZone_ZL_SeatClimate_Extension = 0x32,
  BapFct_ClimateZone_ZR_SeatClimate_Extension = 0x33,
  BapFct_ClimateZone_ZL_SurfaceHeater = 0x34,
  BapFct_ClimateZone_ZR_SurfaceHeater = 0x35,
  BapFct_ClimateZone_ZL_AirFlowIndication = 0x36,
  BapFct_ClimateZone_ZR_AirFlowIndication = 0x37,
  /* Steuergeraet ClimateZone2 */
  BapFct_ClimateZone2_GetAll = 0x01,
  BapFct_ClimateZone2_BAP_Config = 0x02,
  BapFct_ClimateZone2_FunctionList = 0x03,
  BapFct_ClimateZone2_HeartBeat = 0x04,
  BapFct_ClimateZone2_FSG_Control = 0x0d,
  BapFct_ClimateZone2_FSG_Setup = 0x0e,
  BapFct_ClimateZone2_FSG_OperationState = 0x0f,
  BapFct_ClimateZone2_ZL_Temperature = 0x10,
  BapFct_ClimateZone2_ZR_Temperature = 0x11,
  BapFct_ClimateZone2_ZL_AirVolume = 0x12,
  BapFct_ClimateZone2_ZR_AirVolume = 0x13,
  BapFct_ClimateZone2_ZL_AirDistribution = 0x14,
  BapFct_ClimateZone2_ZR_AirDistribution = 0x15,
  BapFct_ClimateZone2_ZL_SeatClimate = 0x16,
  BapFct_ClimateZone2_ZR_SeatClimate = 0x17,
  BapFct_ClimateZone2_ZL_FootwellTemperature = 0x18,
  BapFct_ClimateZone2_ZR_FootwellTemperature = 0x19,
  BapFct_ClimateZone2_ZL_ClimateStyle = 0x1a,
  BapFct_ClimateZone2_ZR_ClimateStyle = 0x1b,
  BapFct_ClimateZone2_ZL_ClimateState = 0x1c,
  BapFct_ClimateZone2_ZR_ClimateState = 0x1d,
  BapFct_ClimateZone2_ZL_IndividualClimatisation = 0x1e,
  BapFct_ClimateZone2_ZR_IndividualClimatisation = 0x1f,
  BapFct_ClimateZone2_ZL_Ionisator = 0x20,
  BapFct_ClimateZone2_ZR_Ionisator = 0x21,
  BapFct_ClimateZone2_ZL_BodyCloseMeasures = 0x22,
  BapFct_ClimateZone2_ZR_BodyCloseMeasures = 0x23,
  BapFct_ClimateZone2_NozzlePositioning = 0x24,
  BapFct_ClimateZone2_NozzleControl = 0x25,
  BapFct_ClimateZone2_NozzleStatus = 0x26,
  BapFct_ClimateZone2_ZL_AUTO = 0x27,
  BapFct_ClimateZone2_ZR_AUTO = 0x28,
  BapFct_ClimateZone2_FootHeater = 0x29,
  BapFct_ClimateZone2_FSG_Setup2 = 0x2a,
  BapFct_ClimateZone2_ZL_IntelligentAUTO = 0x2b,
  BapFct_ClimateZone2_ZR_IntelligentAUTO = 0x2c,
  BapFct_ClimateZone2_AirDistributionPresetList = 0x2d,
  BapFct_ClimateZone2_ZL_AdaptSeatClimateCtrl = 0x2e,
  BapFct_ClimateZone2_ZR_AdaptSeatClimateCtrl = 0x2f,
  BapFct_ClimateZone2_ZL_AutomaticSeatClimate = 0x30,
  BapFct_ClimateZone2_ZR_AutomaticSeatClimate = 0x31,
  BapFct_ClimateZone2_ZL_SeatClimate_Extension = 0x32,
  BapFct_ClimateZone2_ZR_SeatClimate_Extension = 0x33,
  BapFct_ClimateZone2_ZL_SurfaceHeater = 0x34,
  BapFct_ClimateZone2_ZR_SurfaceHeater = 0x35,
  BapFct_ClimateZone2_ZL_AirFlowIndication = 0x36,
  BapFct_ClimateZone2_ZR_AirFlowIndication = 0x37,
  /* Steuergeraet ParkHeater */
  BapFct_ParkHeater_GetAll = 0x01,
  BapFct_ParkHeater_BAP_Config = 0x02,
  BapFct_ParkHeater_FunctionList = 0x03,
  BapFct_ParkHeater_Heartbeat = 0x04,
  BapFct_ParkHeater_FSG_Control = 0x0d,
  BapFct_ParkHeater_FSG_Setup = 0x0e,
  BapFct_ParkHeater_FSG_OperationState = 0x0f,
  BapFct_ParkHeater_AuxHeater = 0x10,
  BapFct_ParkHeater_RunningTime = 0x11,
  BapFct_ParkHeater_Ventilation = 0x12,
  BapFct_ParkHeater_EngineHeater = 0x13,
  BapFct_ParkHeater_HeaterErrorReason = 0x14,
  BapFct_ParkHeater_ActiveTimer = 0x15,
  BapFct_ParkHeater_Timer1 = 0x16,
  BapFct_ParkHeater_Timer2 = 0x17,
  BapFct_ParkHeater_Timer3 = 0x18,
  BapFct_ParkHeater_Weekday = 0x19,
  BapFct_ParkHeater_DefaultStartMode = 0x1a,
  BapFct_ParkHeater_ClimaControl = 0x1b,
  BapFct_ParkHeater_ClimaMode = 0x1c,
  BapFct_ParkHeater_CurrentHeaterState = 0x1d,
  BapFct_ParkHeater_Popup = 0x1e,
  BapFct_ParkHeater_ExtendedConditioning = 0x1f,
  BapFct_ParkHeater_WindowHeating = 0x20,
  BapFct_ParkHeater_UnlockClimating = 0x21,
  BapFct_ParkHeater_TargetTemperature = 0x22,
  BapFct_ParkHeater_AirQuality = 0x23,
  BapFct_ParkHeater_FSG_Setup2 = 0x24,
  BapFct_ParkHeater_RaceConditioning = 0x25,
  BapFct_ParkHeater_RaceConditioningExtended = 0x26,
  BapFct_ParkHeater_RaceMode = 0x27,
  BapFct_ParkHeater_AirCleaner = 0x28,
  BapFct_ParkHeater_ContinousModeControl = 0x29,
  /* Steuergeraet HeadUpDisplay */
  BapFct_HeadUpDisplay_GetAll = 0x01,
  BapFct_HeadUpDisplay_BAP_Config = 0x02,
  BapFct_HeadUpDisplay_FunctionList = 0x03,
  BapFct_HeadUpDisplay_HeartBeat = 0x04,
  BapFct_HeadUpDisplay_FSG_Control = 0x0d,
  BapFct_HeadUpDisplay_FSG_Setup = 0x0e,
  BapFct_HeadUpDisplay_FSG_OperationState = 0x0f,
  BapFct_HeadUpDisplay_Brightness = 0x10,
  BapFct_HeadUpDisplay_DisplayedTopics = 0x11,
  BapFct_HeadUpDisplay_HeightAdjustment = 0x12,
  BapFct_HeadUpDisplay_DisplayContent = 0x13,
  BapFct_HeadUpDisplay_RotationAdjustment = 0x14,
  BapFct_HeadUpDisplay_FSG_Setup2 = 0x15,
  BapFct_HeadUpDisplay_Colour = 0x16,
  BapFct_HeadUpDisplay_License = 0x17,
  BapFct_HeadUpDisplay_Presets = 0x18,
  BapFct_HeadUpDisplay_SectionConfig = 0x19,
  BapFct_HeadUpDisplay_CollectiveDisplayedTopics = 0x1a,
  BapFct_HeadUpDisplay_PSO_ImExport = 0x1b,
  BapFct_HeadUpDisplay_AutoSkinSwitch = 0x1c,
  BapFct_HeadUpDisplay_ConfigurationMode = 0x1d,
  BapFct_HeadUpDisplay_FSG_Setup3 = 0x1e,
  BapFct_HeadUpDisplay_Layout = 0x1f,
  BapFct_HeadUpDisplay_DisplayedTopicsExtended = 0x20,
  BapFct_HeadUpDisplay_ColourSkinChoice = 0x21,
  /* Steuergeraet ACC */
  BapFct_ACC_GetAll = 0x01,
  BapFct_ACC_BAP_Config = 0x02,
  BapFct_ACC_FunctionList = 0x03,
  BapFct_ACC_HeartBeat = 0x04,
  BapFct_ACC_FSG_OperationState = 0x0f,
  BapFct_ACC_Gong = 0x10,
  BapFct_ACC_GongVolume = 0x11,
  BapFct_ACC_DefaultMode = 0x12,
  BapFct_ACC_Timegap = 0x13,
  BapFct_ACC_DrivingProgram = 0x14,
  BapFct_ACC_CurveAssist = 0x15,
  BapFct_ACC_SpeedLimitAdoption = 0x16,
  BapFct_ACC_SpeedLimitOffset = 0x17,
  BapFct_ACC_TrafficJamAssistent = 0x18,
  BapFct_ACC_DistanceWarning = 0x19,
  BapFct_ACC_FSG_Setup = 0x1a,
  BapFct_ACC_FSG_Control = 0x1b,
  BapFct_ACC_PACC_Sensibility = 0x1c,
  BapFct_ACC_PACC_MaxSpeed = 0x1d,
  BapFct_ACC_PACC_MeanVelocity = 0x1e,
  BapFct_ACC_PACC_MeanConsumption = 0x1f,
  BapFct_ACC_PACC_CoastingPercentage = 0x20,
  BapFct_ACC_PACC_DrivingProgram = 0x21,
  BapFct_ACC_PACC_Systemstate = 0x22,
  BapFct_ACC_CrossRail = 0x23,
  BapFct_ACC_TurnAssist = 0x24,
  BapFct_ACC_EvasiveSteeringSupport = 0x25,
  BapFct_ACC_DistanceWarningTimeGap = 0x26,
  BapFct_ACC_TrafficJamAssistent_Control = 0x27,
  BapFct_ACC_TrafficLightAssist = 0x28,
  BapFct_ACC_PSO_ImExport = 0x29,
  BapFct_ACC_PACC_SpeedLimitOffset = 0x2a,
  BapFct_ACC_TrafficJamTailEndAssist = 0x2b,
  BapFct_ACC_RadarfrontendControl = 0x2c,
  BapFct_ACC_StopSignAssist = 0x2d,
  BapFct_ACC_SwarmSpeedAssist = 0x2e,
  BapFct_ACC_PredictiveSpeedControl = 0x2f,
  BapFct_ACC_TrafficLightStopSignAssist = 0x30,
  BapFct_ACC_pAccOffset = 0x31,
  BapFct_ACC_DistanceControl = 0x32,
  BapFct_ACC_AdaptiveTimegap = 0x33,
  BapFct_ACC_SetOnAcceleratorPedal = 0x34,
  BapFct_ACC_TriggerOnButton = 0x35,
  BapFct_ACC_RightofWayAssist = 0x36,
  BapFct_ACC_pAccSpeedLimitAdoption = 0x37,
  BapFct_ACC_TravelSpeed = 0x38,
  BapFct_ACC_RoutePilot = 0x39,
  BapFct_ACC_Views = 0x3a,
  /* Steuergeraet RDK */
  BapFct_RDK_GetAll = 0x01,
  BapFct_RDK_BAP_Config = 0x02,
  BapFct_RDK_FunctionList = 0x03,
  BapFct_RDK_Heartbeat = 0x04,
  BapFct_RDK_FSG_Control = 0x0d,
  BapFct_RDK_FSG_Setup = 0x0e,
  BapFct_RDK_FSG_OperationState = 0x0f,
  BapFct_RDK_ActualState = 0x10,
  BapFct_RDK_ActualPressure = 0x11,
  BapFct_RDK_ActualTemperature = 0x12,
  BapFct_RDK_RequiredPressure = 0x13,
  BapFct_RDK_TyreList = 0x14,
  BapFct_RDK_SavePressure = 0x15,
  BapFct_RDK_SelectedTyre = 0x16,
  BapFct_RDK_DifferentialPressure = 0x17,
  BapFct_RDK_ResidualBatteryLifetime = 0x18,
  BapFct_RDK_SelectedPressureLevel = 0x19,
  BapFct_RDK_SelectedWheelType = 0x1a,
  BapFct_RDK_RaceCircuitMode = 0x1b,
  BapFct_RDK_RequiredPressure_TempDep = 0x1c,
  BapFct_RDK_PressureModification = 0x1d,
  /* Steuergeraet InteriorLight */
  BapFct_InteriorLight_GetAll = 0x01,
  BapFct_InteriorLight_BAP_Config = 0x02,
  BapFct_InteriorLight_FunctionList = 0x03,
  BapFct_InteriorLight_Heartbeat = 0x04,
  BapFct_InteriorLight_FSG_Control = 0x0d,
  BapFct_InteriorLight_FSG_Setup = 0x0e,
  BapFct_InteriorLight_FSG_OperationState = 0x0f,
  BapFct_InteriorLight_Colour = 0x10,
  BapFct_InteriorLight_AmbianceLighting = 0x11,
  BapFct_InteriorLight_EnvironmentDependence = 0x12,
  BapFct_InteriorLight_TemperatureDependence = 0x13,
  BapFct_InteriorLight_SpeedDependence = 0x14,
  BapFct_InteriorLight_Brightness = 0x15,
  BapFct_InteriorLight_IlluminationSet1 = 0x16,
  BapFct_InteriorLight_IlluminationSet2 = 0x17,
  BapFct_InteriorLight_IlluminationSet3 = 0x18,
  BapFct_InteriorLight_IlluminationSet4 = 0x19,
  BapFct_InteriorLight_IlluminationSet5 = 0x1a,
  BapFct_InteriorLight_IlluminationSet6 = 0x1b,
  BapFct_InteriorLight_IlluminationSet7 = 0x1c,
  BapFct_InteriorLight_IlluminationSet8 = 0x1d,
  BapFct_InteriorLight_FSG_Setup2 = 0x1e,
  BapFct_InteriorLight_ActiveProfile = 0x1f,
  BapFct_InteriorLight_AmbientLightColor_RGB = 0x20,
  BapFct_InteriorLight_ContourLightColor_RGB = 0x21,
  BapFct_InteriorLight_IlluminationProfile1 = 0x22,
  BapFct_InteriorLight_IlluminationProfile2 = 0x23,
  BapFct_InteriorLight_IlluminationProfile3 = 0x24,
  BapFct_InteriorLight_IlluminationProfile4 = 0x25,
  BapFct_InteriorLight_IlluminationProfile5 = 0x26,
  BapFct_InteriorLight_IlluminationProfile6 = 0x27,
  BapFct_InteriorLight_IlluminationProfile7 = 0x28,
  BapFct_InteriorLight_IlluminationProfile8 = 0x29,
  BapFct_InteriorLight_RGBColorList = 0x2a,
  BapFct_InteriorLight_FollowUpTime = 0x2b,
  BapFct_InteriorLight_DoorContact = 0x2c,
  BapFct_InteriorLight_MatrixReadingLight_Switch = 0x2d,
  BapFct_InteriorLight_ZL_MatrixReadingLight_Setup = 0x2e,
  BapFct_InteriorLight_ZR_MatrixReadingLight_Setup = 0x2f,
  BapFct_InteriorLight_MatrixReadingLight_SpclPos = 0x30,
  BapFct_InteriorLight_PSO_ImExport = 0x31,
  BapFct_InteriorLight_FunctionalAmbianceLightingList = 0x32,
  BapFct_InteriorLight_ColorScheme = 0x33,
  BapFct_InteriorLight_SchemeControl = 0x34,
  BapFct_InteriorLight_Atmospheres = 0x35,
  BapFct_InteriorLight_Wellbeing = 0x36,
  BapFct_InteriorLight_FSG_Setup3 = 0x37,
  BapFct_InteriorLight_IlluminationScene = 0x38,
  BapFct_InteriorLight_ColorLayer_Setup = 0x39,
  /* Steuergeraet ExteriorLight */
  BapFct_ExteriorLight_GetAll = 0x01,
  BapFct_ExteriorLight_BAP_Config = 0x02,
  BapFct_ExteriorLight_FunctionList = 0x03,
  BapFct_ExteriorLight_HeartBeat = 0x04,
  BapFct_ExteriorLight_FSG_Control = 0x0d,
  BapFct_ExteriorLight_FSG_Setup = 0x0e,
  BapFct_ExteriorLight_FSG_OperationState = 0x0f,
  BapFct_ExteriorLight_DaytimeRunningLight = 0x10,
  BapFct_ExteriorLight_TouristLight = 0x11,
  BapFct_ExteriorLight_ComingHome = 0x12,
  BapFct_ExteriorLight_LeavingHome = 0x13,
  BapFct_ExteriorLight_LightSensitivity = 0x14,
  BapFct_ExteriorLight_LampErrorDetection = 0x15,
  BapFct_ExteriorLight_Motorwayblinking = 0x16,
  BapFct_ExteriorLight_LampErrorDetection_Trailer = 0x17,
  BapFct_ExteriorLight_AdaptiveLightSystem = 0x18,
  BapFct_ExteriorLight_HeadLightAssistant = 0x19,
  BapFct_ExteriorLight_GlidingHeadLight = 0x1a,
  BapFct_ExteriorLight_MaskedHighBeam = 0x1b,
  BapFct_ExteriorLight_PowerManagement = 0x1c,
  BapFct_ExteriorLight_AutomaticLight = 0x1d,
  BapFct_ExteriorLight_LaserLight = 0x1e,
  BapFct_ExteriorLight_HeadlightRange = 0x1f,
  BapFct_ExteriorLight_FSG_Setup2 = 0x20,
  BapFct_ExteriorLight_Advanced_LH = 0x21,
  BapFct_ExteriorLight_Advanced_CH = 0x22,
  BapFct_ExteriorLight_LightGuidance = 0x23,
  BapFct_ExteriorLight_GuideProjection = 0x24,
  BapFct_ExteriorLight_LightAssistance = 0x25,
  BapFct_ExteriorLight_AssistProjection = 0x26,
  BapFct_ExteriorLight_PSO_ImExport = 0x27,
  BapFct_ExteriorLight_AmbientExteriorLight = 0x28,
  BapFct_ExteriorLight_ManualActivation_CHO = 0x29,
  BapFct_ExteriorLight_AnimationRearLight = 0x2a,
  BapFct_ExteriorLight_AnimationTurnLight = 0x2b,
  BapFct_ExteriorLight_LightSignatures = 0x2c,
  BapFct_ExteriorLight_FSG_Setup3 = 0x2d,
  BapFct_ExteriorLight_HDLight = 0x2e,
  BapFct_ExteriorLight_FunctionalExteriorLight = 0x2f,
  /* Steuergeraet PDC */
  BapFct_PDC_GetAll = 0x01,
  BapFct_PDC_BAP_Config = 0x02,
  BapFct_PDC_FunctionList = 0x03,
  BapFct_PDC_HeartBeat = 0x04,
  BapFct_PDC_FSG_Control = 0x0d,
  BapFct_PDC_FSG_Setup = 0x0e,
  BapFct_PDC_FSG_OperationState = 0x0f,
  BapFct_PDC_Sound_Front = 0x10,
  BapFct_PDC_Sound_Rear = 0x11,
  BapFct_PDC_Spacing_Front = 0x12,
  BapFct_PDC_Spacing_Rear = 0x13,
  BapFct_PDC_APS_Mute = 0x14,
  BapFct_PDC_Display = 0x15,
  BapFct_PDC_DefaultParkingmode = 0x16,
  BapFct_PDC_Trailer = 0x17,
  BapFct_PDC_AutoActivation = 0x18,
  BapFct_PDC_Spacing_Right = 0x19,
  BapFct_PDC_Spacing_Left = 0x1a,
  BapFct_PDC_Sound_Right = 0x1b,
  BapFct_PDC_Sound_Left = 0x1c,
  BapFct_PDC_FlankGuard = 0x1d,
  BapFct_PDC_CrashWarning = 0x1e,
  BapFct_PDC_SteeringInformation = 0x1f,
  BapFct_PDC_SoundReproduction = 0x20,
  BapFct_PDC_Info = 0x21,
  BapFct_PDC_Spacing_Front_Extended = 0x22,
  BapFct_PDC_Spacing_Rear_Extended = 0x23,
  BapFct_PDC_WallDetection = 0x24,
  BapFct_PDC_PLA_Status = 0x25,
  BapFct_PDC_PLA_Bargraph = 0x26,
  BapFct_PDC_PLA_Messages = 0x27,
  BapFct_PDC_PLA_ParkmodeSelection = 0x28,
  BapFct_PDC_PDC_PLA_SystemState = 0x29,
  BapFct_PDC_PDC_Offroad = 0x2a,
  BapFct_PDC_ParkboxVisualisation = 0x2b,
  BapFct_PDC_OPSVisualisation_Position = 0x2c,
  BapFct_PDC_ManeuverAssist_Config = 0x2d,
  BapFct_PDC_ManeuverAssist = 0x2e,
  BapFct_PDC_ManeuverAssist_State = 0x2f,
  BapFct_PDC_IPA_Config = 0x30,
  BapFct_PDC_PiloPa_SystemState = 0x31,
  BapFct_PDC_IPA_Messages = 0x32,
  BapFct_PDC_ContinueDrivingAssist = 0x33,
  BapFct_PDC_FSG_Setup2 = 0x34,
  BapFct_PDC_ParkSideSelection = 0x35,
  BapFct_PDC_PSO_ImExport = 0x36,
  BapFct_PDC_IPA_Parking_Activation = 0x37,
  BapFct_PDC_PLA_MapList = 0x38,
  BapFct_PDC_ParkboxList_AWC = 0x39,
  BapFct_PDC_APA_ManeuverDetails = 0x3a,
  BapFct_PDC_IPA_AutoActivation = 0x3b,
  BapFct_PDC_IPA_SoundIndication = 0x3c,
  BapFct_PDC_RA_Messages = 0x3d,
  BapFct_PDC_PLA_MapList_dynamic = 0x3e,
  /* Steuergeraet VPS */
  BapFct_VPS_GetAll = 0x01,
  BapFct_VPS_BAP_Config = 0x02,
  BapFct_VPS_FunctionList = 0x03,
  BapFct_VPS_HeartBeat = 0x04,
  BapFct_VPS_FSG_Control = 0x0d,
  BapFct_VPS_FSG_Setup = 0x0e,
  BapFct_VPS_FSG_OperationState = 0x0f,
  BapFct_VPS_FollowUp_Time = 0x10,
  BapFct_VPS_DefaultModeRV = 0x11,
  BapFct_VPS_DefaultModeFV = 0x12,
  BapFct_VPS_DefaultModeSV = 0x13,
  BapFct_VPS_DefaultModeBV = 0x14,
  BapFct_VPS_DefaultView = 0x15,
  BapFct_VPS_Info = 0x16,
  BapFct_VPS_Color = 0x17,
  BapFct_VPS_Contrast = 0x18,
  BapFct_VPS_Brightness = 0x19,
  BapFct_VPS_Display = 0x1a,
  BapFct_VPS_DynamicParkingMode = 0x1b,
  BapFct_VPS_OPS_Overlay = 0x1c,
  BapFct_VPS_CameraStates = 0x1d,
  BapFct_VPS_3D_BirdView_Config = 0x1e,
  BapFct_VPS_3D_BirdView = 0x1f,
  BapFct_VPS_ExtCamera_Config = 0x20,
  BapFct_VPS_ExtCamera_ManActivation = 0x21,
  BapFct_VPS_SystemState = 0x22,
  BapFct_VPS_RimProtection = 0x23,
  BapFct_VPS_CameraCleaning = 0x24,
  BapFct_VPS_FSG_Setup2 = 0x25,
  BapFct_VPS_FavoriteList = 0x26,
  BapFct_VPS_Switch_2D_3D = 0x27,
  BapFct_VPS_Guidelines = 0x28,
  BapFct_VPS_Messages = 0x29,
  BapFct_VPS_PSO_ImExport = 0x2a,
  BapFct_VPS_AutoCameraCleaning = 0x2b,
  /* Steuergeraet Wiper_Comfort */
  BapFct_Wiper_Comfort_GetAll = 0x01,
  BapFct_Wiper_Comfort_BAP_Config = 0x02,
  BapFct_Wiper_Comfort_FunctionList = 0x03,
  BapFct_Wiper_Comfort_HeartBeat = 0x04,
  BapFct_Wiper_Comfort_FSG_Control = 0x0d,
  BapFct_Wiper_Comfort_FSG_OperationState = 0x0f,
  BapFct_Wiper_Comfort_ServicePosition = 0x10,
  BapFct_Wiper_Comfort_WinterPosition = 0x11,
  BapFct_Wiper_Comfort_RearWiping = 0x12,
  BapFct_Wiper_Comfort_TearsWiping = 0x13,
  BapFct_Wiper_Comfort_RainSensorOFF = 0x14,
  BapFct_Wiper_Comfort_RainSensorConfig = 0x15,
  BapFct_Wiper_Comfort_EasyEntrySteeringColumn = 0x16,
  BapFct_Wiper_Comfort_CameraCleaning = 0x17,
  /* Steuergeraet Doorlocking */
  BapFct_Doorlocking_GetAll = 0x01,
  BapFct_Doorlocking_BAP_Config = 0x02,
  BapFct_Doorlocking_FunctionList = 0x03,
  BapFct_Doorlocking_Heartbeat = 0x04,
  BapFct_Doorlocking_FSG_Control = 0x0d,
  BapFct_Doorlocking_FSG_Setup = 0x0e,
  BapFct_Doorlocking_FSG_OperationState = 0x0f,
  BapFct_Doorlocking_ComfortOpen = 0x10,
  BapFct_Doorlocking_CentralLocking = 0x11,
  BapFct_Doorlocking_RainClosing = 0x12,
  BapFct_Doorlocking_TheftProtectionSensorSetup = 0x13,
  BapFct_Doorlocking_AcknowledgeHonk = 0x14,
  BapFct_Doorlocking_RearBlind = 0x15,
  BapFct_Doorlocking_TurnIndicatorRepeat = 0x16,
  BapFct_Doorlocking_AutoLock = 0x17,
  BapFct_Doorlocking_AutoUnLock = 0x18,
  BapFct_Doorlocking_MirrorFoldIn = 0x19,
  BapFct_Doorlocking_Message = 0x1a,
  BapFct_Doorlocking_VehicleLockState = 0x1b,
  BapFct_Doorlocking_WindowState = 0x1c,
  BapFct_Doorlocking_BootOpen = 0x1d,
  BapFct_Doorlocking_BootClose = 0x1e,
  BapFct_Doorlocking_RemoteControlChallenge = 0x1f,
  BapFct_Doorlocking_RemoteControlAuthentication = 0x20,
  BapFct_Doorlocking_RemoteControlSignature = 0x21,
  BapFct_Doorlocking_RemoteControl_Horn = 0x22,
  BapFct_Doorlocking_RemoteControl_Blinking = 0x23,
  BapFct_Doorlocking_UserList = 0x24,
  BapFct_Doorlocking_ActiveUser = 0x25,
  BapFct_Doorlocking_UserProfileOnOff = 0x26,
  BapFct_Doorlocking_UserProfileControl = 0x27,
  BapFct_Doorlocking_FSG_Setup2 = 0x28,
  BapFct_Doorlocking_WindowAutoClose = 0x29,
  BapFct_Doorlocking_Blinds_Control = 0x2a,
  BapFct_Doorlocking_Prompt = 0x2b,
  BapFct_Doorlocking_SideBlinds_Control = 0x2c,
  BapFct_Doorlocking_Keyless = 0x2d,
  BapFct_Doorlocking_PSO_ImExport = 0x2e,
  BapFct_Doorlocking_KeylessAdvanced = 0x2f,
  BapFct_Doorlocking_VehicleLockControl = 0x30,
  BapFct_Doorlocking_FrontHoodControl = 0x31,
  BapFct_Doorlocking_BootControl = 0x32,
  BapFct_Doorlocking_BootOpen_State = 0x33,
  BapFct_Doorlocking_AllWindowAutomatic = 0x34,
  BapFct_Doorlocking_Clamp15Deactivation = 0x35,
  BapFct_Doorlocking_ChildPresenceDetect = 0x36,
  BapFct_Doorlocking_FSG_Setup3 = 0x37,
  BapFct_Doorlocking_ChildPresenceDetectWarning = 0x38,
  BapFct_Doorlocking_ElectricGloveCompartmentStatus = 0x39,
  BapFct_Doorlocking_RemoteControlFunctions = 0x3a,
  BapFct_Doorlocking_AutomaticDoorFunctions = 0x3b,
  BapFct_Doorlocking_ValetMode = 0x3c,
  /* Steuergeraet Mirror */
  BapFct_Mirror_GetAll = 0x01,
  BapFct_Mirror_BAP_Config = 0x02,
  BapFct_Mirror_FunctionList = 0x03,
  BapFct_Mirror_HeartBeat = 0x04,
  BapFct_Mirror_FSG_Control = 0x0d,
  BapFct_Mirror_FSG_Setup = 0x0e,
  BapFct_Mirror_FSG_OperationState = 0x0f,
  BapFct_Mirror_MirrorSetup = 0x10,
  BapFct_Mirror_MirrorControl = 0x11,
  /* Steuergeraet BC_MFA */
  BapFct_BC_MFA_GetAll = 0x01,
  BapFct_BC_MFA_BAP_Config = 0x02,
  BapFct_BC_MFA_FunctionList = 0x03,
  BapFct_BC_MFA_HeartBeat = 0x04,
  BapFct_BC_MFA_FSG_Control = 0x0d,
  BapFct_BC_MFA_FSG_Setup = 0x0e,
  BapFct_BC_MFA_FSG_OperationState = 0x0f,
  BapFct_BC_MFA_DisplayConfiguration = 0x10,
  BapFct_BC_MFA_Reset = 0x11,
  BapFct_BC_MFA_SpeedWarning = 0x12,
  BapFct_BC_MFA_CurrentConsumption = 0x13,
  BapFct_BC_MFA_CurrentRange = 0x14,
  BapFct_BC_MFA_TotalDistance = 0x15,
  BapFct_BC_MFA_ShortTermFIS1 = 0x16,
  BapFct_BC_MFA_ShortTermFIS2 = 0x17,
  BapFct_BC_MFA_LongTermFIS1 = 0x18,
  BapFct_BC_MFA_LongTermFIS2 = 0x19,
  BapFct_BC_MFA_CycleFIS1 = 0x1a,
  BapFct_BC_MFA_CycleFIS2 = 0x1b,
  BapFct_BC_MFA_ResetTimeStampsFIS = 0x1c,
  BapFct_BC_MFA_TankLevel = 0x1d,
  BapFct_BC_MFA_RefuelVolume = 0x1e,
  BapFct_BC_MFA_VehicleState = 0x1f,
  BapFct_BC_MFA_OutsideTemperature = 0x20,
  BapFct_BC_MFA_OilTemperature = 0x21,
  BapFct_BC_MFA_CoolantTemperature = 0x22,
  BapFct_BC_MFA_MaxValues = 0x23,
  BapFct_BC_MFA_PSO_ImExport = 0x24,
  BapFct_BC_MFA_SpeedWarning2 = 0x25,
  BapFct_BC_MFA_ActiveWarningList = 0x26,
  BapFct_BC_MFA_TripDistance = 0x27,
  BapFct_BC_MFA_ConfirmationConfig = 0x28,
  /* Steuergeraet Seat */
  BapFct_Seat_GetAll = 0x01,
  BapFct_Seat_BAP_Config = 0x02,
  BapFct_Seat_FunctionList = 0x03,
  BapFct_Seat_Heartbeat = 0x04,
  BapFct_Seat_FSG_Control = 0x0d,
  BapFct_Seat_FSG_Setup = 0x0e,
  BapFct_Seat_FSG_OperationState = 0x0f,
  BapFct_Seat_RadiokeyControl = 0x10,
  BapFct_Seat_SeatMemoryBlockade = 0x11,
  BapFct_Seat_SpecialPosition = 0x12,
  BapFct_Seat_SG_Darstellung = 0x13,
  BapFct_Seat_DP_Presentation = 0x14,
  BapFct_Seat_SuppressVisualisation = 0x15,
  BapFct_Seat_Massage = 0x16,
  BapFct_Seat_EasyEntryFront = 0x17,
  BapFct_Seat_EasyEntryRear = 0x18,
  BapFct_Seat_CodriverSettingsFromDriver = 0x19,
  BapFct_Seat_CodriverSettingsFromRear = 0x1a,
  BapFct_Seat_Switch = 0x1b,
  BapFct_Seat_VisualisationConfig = 0x1c,
  BapFct_Seat_SeatAdjustment = 0x1d,
  BapFct_Seat_DeleteSpecialPosition = 0x1e,
  BapFct_Seat_CodriverSetFromRearAct = 0x1f,
  BapFct_Seat_RestSeatStatus = 0x20,
  BapFct_Seat_MoveRearSeatDisplay = 0x21,
  BapFct_Seat_FoldHeadRest = 0x22,
  BapFct_Seat_Switch2 = 0x23,
  BapFct_Seat_VisualisationConfig2 = 0x24,
  BapFct_Seat_MassageSwitch = 0x25,
  BapFct_Seat_PremiumMassage = 0x26,
  BapFct_Seat_PremiumMassageSwitch = 0x27,
  BapFct_Seat_PSO_ImExport = 0x28,
  BapFct_Seat_MassageProgramList = 0x29,
  BapFct_Seat_FootSize = 0x2a,
  BapFct_Seat_BodySize = 0x2b,
  BapFct_Seat_PremiumMassageProgramList = 0x2c,
  BapFct_Seat_CabinScene_Settings = 0x2d,
  BapFct_Seat_CabinScene_Config = 0x2e,
  BapFct_Seat_FSG_Setup_SpecialPosition2 = 0x2f,
  BapFct_Seat_SpecialPosition2_Setting = 0x30,
  BapFct_Seat_SpecialPosition2_State = 0x31,
  BapFct_Seat_SpecialPosition2 = 0x32,
  BapFct_Seat_Massage_2 = 0x33,
  BapFct_Seat_4DSound = 0x34,
  BapFct_Seat_VisualisationConfig3 = 0x35,
  BapFct_Seat_VisualisationConfig4DSound = 0x36,
  /* Steuergeraet Clock */
  BapFct_Clock_GetAll = 0x01,
  BapFct_Clock_BAP_Config = 0x02,
  BapFct_Clock_FunctionList = 0x03,
  BapFct_Clock_HeartBeat = 0x04,
  BapFct_Clock_FSG_Control = 0x0d,
  BapFct_Clock_FSG_Setup = 0x0e,
  BapFct_Clock_FSG_OperationState = 0x0f,
  BapFct_Clock_Date = 0x10,
  BapFct_Clock_Time = 0x11,
  BapFct_Clock_TimeZone = 0x12,
  BapFct_Clock_DayLightSaving = 0x13,
  BapFct_Clock_Clock_Mode = 0x14,
  BapFct_Clock_Reminder1 = 0x15,
  BapFct_Clock_Reminder2 = 0x16,
  BapFct_Clock_Buzzer = 0x17,
  BapFct_Clock_GPS_Sync = 0x18,
  BapFct_Clock_RDS_Sync = 0x19,
  BapFct_Clock_DayLightSaving_auto = 0x1a,
  BapFct_Clock_Buzzer1 = 0x1b,
  BapFct_Clock_Buzzer2 = 0x1c,
  BapFct_Clock_Buzzer3 = 0x1d,
  BapFct_Clock_Buzzer4 = 0x1e,
  BapFct_Clock_Stopwatch_State = 0x1f,
  BapFct_Clock_Stopwatch_LastSplittime = 0x20,
  BapFct_Clock_Stopwatch_LastLaptime = 0x21,
  BapFct_Clock_Stopwatch_FastestLaptime = 0x22,
  BapFct_Clock_Stopwatch_SlowestLaptime = 0x23,
  BapFct_Clock_Stopwatch_Control = 0x24,
  BapFct_Clock_Stopwatch_Timer = 0x25,
  /* Steuergeraet SIA */
  BapFct_SIA_GetAll = 0x01,
  BapFct_SIA_BAP_Config = 0x02,
  BapFct_SIA_FunctionList = 0x03,
  BapFct_SIA_HeartBeat = 0x04,
  BapFct_SIA_FSG_Control = 0x0d,
  BapFct_SIA_FSG_OperationState = 0x0f,
  BapFct_SIA_Distance_Oil = 0x10,
  BapFct_SIA_Time_Oil = 0x11,
  BapFct_SIA_Inspection_Distance = 0x12,
  BapFct_SIA_Inspection_Time = 0x13,
  BapFct_SIA_Reset = 0x14,
  BapFct_SIA_Distance_Oil_User = 0x15,
  BapFct_SIA_Distance_AirFilter_User = 0x16,
  BapFct_SIA_Distance_OilFilter_User = 0x17,
  BapFct_SIA_Inspection_Distance_User = 0x18,
  BapFct_SIA_Daily_AvgMileage = 0x19,
  BapFct_SIA_Service_History = 0x1a,
  /* Steuergeraet UnitMaster */
  BapFct_UnitMaster_GetAll = 0x01,
  BapFct_UnitMaster_BAP_Config = 0x02,
  BapFct_UnitMaster_FunctionList = 0x03,
  BapFct_UnitMaster_HeartBeat = 0x04,
  BapFct_UnitMaster_FSG_Control = 0x0d,
  BapFct_UnitMaster_FSG_Setup = 0x0e,
  BapFct_UnitMaster_FSG_OperationState = 0x0f,
  BapFct_UnitMaster_Language = 0x10,
  BapFct_UnitMaster_TemperatureUnit = 0x11,
  BapFct_UnitMaster_DistanceSpeedUnit = 0x12,
  BapFct_UnitMaster_PressureUnit = 0x13,
  BapFct_UnitMaster_VolumeUnit = 0x14,
  BapFct_UnitMaster_Clock_Date = 0x15,
  BapFct_UnitMaster_ConsumptionUnit_Liquid = 0x16,
  BapFct_UnitMaster_ConsumptionUnit_Gaseous = 0x17,
  BapFct_UnitMaster_ConsumptionUnit_Electrical = 0x18,
  BapFct_UnitMaster_SkinConfig = 0x19,
  BapFct_UnitMaster_Skin = 0x1a,
  BapFct_UnitMaster_WeightUnit = 0x1b,
  BapFct_UnitMaster_PSO_ImExport = 0x1c,
  BapFct_UnitMaster_FSG_Setup2 = 0x1d,
  BapFct_UnitMaster_Background = 0x1e,
  /* Steuergeraet HomeLink */
  BapFct_HomeLink_GetAll = 0x01,
  BapFct_HomeLink_BAP_Config = 0x02,
  BapFct_HomeLink_FunctionList = 0x03,
  BapFct_HomeLink_HeartBeat = 0x04,
  BapFct_HomeLink_FSG_Control = 0x0d,
  BapFct_HomeLink_FSG_Setup = 0x0e,
  BapFct_HomeLink_FSG_OperationState = 0x0f,
  BapFct_HomeLink_ButtonList = 0x10,
  BapFct_HomeLink_StartLearning = 0x11,
  BapFct_HomeLink_Synchronise = 0x12,
  BapFct_HomeLink_OpenDoor = 0x13,
  BapFct_HomeLink_DestinationReached = 0x14,
  BapFct_HomeLink_Delete = 0x15,
  BapFct_HomeLink_VersionInfo = 0x16,
  BapFct_HomeLink_Display = 0x17,
  BapFct_HomeLink_ButtonState = 0x18,
  /* Steuergeraet Charisma */
  BapFct_Charisma_GetAll = 0x01,
  BapFct_Charisma_BAP_Config = 0x02,
  BapFct_Charisma_FunctionList = 0x03,
  BapFct_Charisma_HeartBeat = 0x04,
  BapFct_Charisma_FSG_Control = 0x0d,
  BapFct_Charisma_FSG_Setup = 0x0e,
  BapFct_Charisma_FSG_OperationState = 0x0f,
  BapFct_Charisma_ProfileConfiguration = 0x10,
  BapFct_Charisma_SetupProfile = 0x11,
  BapFct_Charisma_DP_Presentation = 0x12,
  BapFct_Charisma_Trailer = 0x13,
  BapFct_Charisma_ProfilesModification = 0x14,
  BapFct_Charisma_ProgrammableButtonControl = 0x15,
  BapFct_Charisma_SetupOperationMode = 0x16,
  BapFct_Charisma_OperationModeModification = 0x17,
  BapFct_Charisma_ProfilesModification2 = 0x18,
  BapFct_Charisma_ProfileConfiguration_Extended = 0x19,
  BapFct_Charisma_Sound = 0x1a,
  BapFct_Charisma_HybridSport = 0x1b,
  BapFct_Charisma_OperationModePreselection = 0x1c,
  BapFct_Charisma_PSO_ImExport = 0x1d,
  BapFct_Charisma_FSG_Setup2 = 0x1e,
  BapFct_Charisma_NextProfile = 0x1f,
  BapFct_Charisma_LastmodeSetup = 0x20,
  BapFct_Charisma_ResetProfile = 0x21,
  BapFct_Charisma_ProfileChanged = 0x22,
  BapFct_Charisma_FavoriteProfile = 0x23,
  BapFct_Charisma_ProfilesModification3 = 0x24,
  BapFct_Charisma_SetupProfile_LM = 0x25,
  BapFct_Charisma_SetupOperationMode_LM = 0x26,
  BapFct_Charisma_eMotionSelection = 0x27,
  /* Steuergeraet LDW_HCA */
  BapFct_LDW_HCA_GetAll = 0x01,
  BapFct_LDW_HCA_BAP_Config = 0x02,
  BapFct_LDW_HCA_FunctionList = 0x03,
  BapFct_LDW_HCA_HeartBeat = 0x04,
  BapFct_LDW_HCA_FSG_Control = 0x0d,
  BapFct_LDW_HCA_FSG_Setup = 0x0e,
  BapFct_LDW_HCA_FSG_OperationState = 0x0f,
  BapFct_LDW_HCA_WarningIntensity = 0x10,
  BapFct_LDW_HCA_WarningTime = 0x11,
  BapFct_LDW_HCA_Systemmode = 0x12,
  BapFct_LDW_HCA_WarningSound = 0x13,
  BapFct_LDW_HCA_LaneDepartureWarning = 0x14,
  BapFct_LDW_HCA_EmergencyAssist = 0x15,
  BapFct_LDW_HCA_PSO_ImExport = 0x16,
  BapFct_LDW_HCA_SportDriveRecognition = 0x17,
  BapFct_LDW_HCA_RequestEmergencyAssist = 0x18,
  BapFct_LDW_HCA_CutCorner = 0x19,
  BapFct_LDW_HCA_ChangeLane = 0x1a,
  BapFct_LDW_HCA_FunctionModification = 0x1b,
  BapFct_LDW_HCA_LateralLongitudinalAssistance = 0x1c,
  BapFct_LDW_HCA_FSG_Control_LastMode = 0x1d,
  BapFct_LDW_HCA_Reduced_aLDW_mode = 0x1e,
  BapFct_LDW_HCA_LaneCentering = 0x1f,
  BapFct_LDW_HCA_HandsFreeDriving = 0x20,
  BapFct_LDW_HCA_SystemTriggeredLaneChange = 0x21,
  BapFct_LDW_HCA_FollowTheNavi = 0x22,
  BapFct_LDW_HCA_VisualAcceptedLaneChange = 0x23,
  BapFct_LDW_HCA_LegalDisclaimer = 0x24,
  BapFct_LDW_HCA_HandsFreeDriving2 = 0x25,
  /* Steuergeraet SWA */
  BapFct_SWA_GetAll = 0x01,
  BapFct_SWA_BAP_Config = 0x02,
  BapFct_SWA_FunctionList = 0x03,
  BapFct_SWA_Heartbeat = 0x04,
  BapFct_SWA_FSG_OperationState = 0x0f,
  BapFct_SWA_Country = 0x10,
  BapFct_SWA_Brightness = 0x11,
  BapFct_SWA_WarningTime = 0x12,
  BapFct_SWA_FSG_Control = 0x13,
  BapFct_SWA_Gong = 0x14,
  BapFct_SWA_Gong_Volume = 0x15,
  BapFct_SWA_FSG_Setup = 0x16,
  BapFct_SWA_RCTA = 0x17,
  BapFct_SWA_RCTA_SensorData = 0x18,
  BapFct_SWA_ExitAssist = 0x19,
  BapFct_SWA_RCTA_Messages = 0x1a,
  BapFct_SWA_RCTA_BrakeIntervention = 0x1b,
  BapFct_SWA_PSO_ImExport = 0x1c,
  BapFct_SWA_SideAssist = 0x1d,
  BapFct_SWA_RadarfrontendControl = 0x1e,
  BapFct_SWA_ExitAssist_LM = 0x1f,
  BapFct_SWA_SideAssist_LM = 0x20,
  /* Steuergeraet AWV */
  BapFct_AWV_GetAll = 0x01,
  BapFct_AWV_BAP_Config = 0x02,
  BapFct_AWV_FunctionList = 0x03,
  BapFct_AWV_HeartBeat = 0x04,
  BapFct_AWV_FSG_Setup = 0x0c,
  BapFct_AWV_FSG_Control = 0x0d,
  BapFct_AWV_FSG_OperationState = 0x0f,
  BapFct_AWV_Gong = 0x10,
  BapFct_AWV_GongVolume = 0x11,
  BapFct_AWV_AdvanceWarning = 0x12,
  BapFct_AWV_BrakeJerk = 0x13,
  BapFct_AWV_EmergencyBrake = 0x14,
  BapFct_AWV_DistanceWarning = 0x15,
  BapFct_AWV_AdvanceWarning_Timegap = 0x16,
  BapFct_AWV_PSO_ImExport = 0x17,
  BapFct_AWV_EventData = 0x18,
  BapFct_AWV_FrontCrossingTrafficInfo = 0x19,
  BapFct_AWV_FrontCrossingTrafficAssist = 0x1a,
  BapFct_AWV_FTA_SensorData = 0x1b,
  BapFct_AWV_RadarfrontendControl = 0x1c,
  BapFct_AWV_DistanceWarning2 = 0x1d,
  BapFct_AWV_TurnAssist = 0x1e,
  BapFct_AWV_EvasiveSteeringSupport = 0x1f,
  /* Steuergeraet Hybrid */
  BapFct_Hybrid_GetAll = 0x01,
  BapFct_Hybrid_BAP_Config = 0x02,
  BapFct_Hybrid_FunctionList = 0x03,
  BapFct_Hybrid_Heartbeat = 0x04,
  BapFct_Hybrid_FSG_Control = 0x0d,
  BapFct_Hybrid_FSG_Setup = 0x0e,
  BapFct_Hybrid_FSG_OperationState = 0x0f,
  BapFct_Hybrid_Hybrid_Energyflow_State = 0x10,
  BapFct_Hybrid_Hybrid_ChargeLevel = 0x11,
  BapFct_Hybrid_Hybrid_Energyflow = 0x12,
  BapFct_Hybrid_Hybrid_RecoveredEnergy = 0x13,
  BapFct_Hybrid_TargetRange = 0x14,
  BapFct_Hybrid_EnergyAssistControl = 0x15,
  BapFct_Hybrid_EnergyAssistState = 0x16,
  BapFct_Hybrid_InhibitReason = 0x17,
  BapFct_Hybrid_ActivePedal = 0x18,
  BapFct_Hybrid_HybridChargeTrend = 0x19,
  /* Steuergeraet SeatBF */
  BapFct_SeatBF_GetAll = 0x01,
  BapFct_SeatBF_BAP_Config = 0x02,
  BapFct_SeatBF_FunctionList = 0x03,
  BapFct_SeatBF_Heartbeat = 0x04,
  BapFct_SeatBF_FSG_Control = 0x0d,
  BapFct_SeatBF_FSG_Setup = 0x0e,
  BapFct_SeatBF_FSG_OperationState = 0x0f,
  BapFct_SeatBF_RadiokeyControl = 0x10,
  BapFct_SeatBF_SeatMemoryBlockade = 0x11,
  BapFct_SeatBF_SpecialPosition = 0x12,
  BapFct_SeatBF_SG_Darstellung = 0x13,
  BapFct_SeatBF_DP_Presentation = 0x14,
  BapFct_SeatBF_SuppressVisualisation = 0x15,
  BapFct_SeatBF_Massage = 0x16,
  BapFct_SeatBF_EasyEntryFront = 0x17,
  BapFct_SeatBF_EasyEntryRear = 0x18,
  BapFct_SeatBF_CodriverSettingsFromDriver = 0x19,
  BapFct_SeatBF_CodriverSettingsFromRear = 0x1a,
  BapFct_SeatBF_Switch = 0x1b,
  BapFct_SeatBF_VisualisationConfig = 0x1c,
  BapFct_SeatBF_SeatAdjustment = 0x1d,
  BapFct_SeatBF_DeleteSpecialPosition = 0x1e,
  BapFct_SeatBF_CodriverSetFromRearAct = 0x1f,
  BapFct_SeatBF_RestSeatStatus = 0x20,
  BapFct_SeatBF_MoveRearSeatDisplay = 0x21,
  BapFct_SeatBF_FoldHeadRest = 0x22,
  BapFct_SeatBF_Switch2 = 0x23,
  BapFct_SeatBF_VisualisationConfig2 = 0x24,
  BapFct_SeatBF_MassageSwitch = 0x25,
  BapFct_SeatBF_PremiumMassage = 0x26,
  BapFct_SeatBF_PremiumMassageSwitch = 0x27,
  BapFct_SeatBF_PSO_ImExport = 0x28,
  BapFct_SeatBF_MassageProgramList = 0x29,
  BapFct_SeatBF_FootSize = 0x2a,
  BapFct_SeatBF_BodySize = 0x2b,
  BapFct_SeatBF_PremiumMassageProgramList = 0x2c,
  BapFct_SeatBF_CabinScene_Settings = 0x2d,
  BapFct_SeatBF_CabinScene_Config = 0x2e,
  BapFct_SeatBF_FSG_Setup_SpecialPosition2 = 0x2f,
  BapFct_SeatBF_SpecialPosition2_Setting = 0x30,
  BapFct_SeatBF_SpecialPosition2_State = 0x31,
  BapFct_SeatBF_SpecialPosition2 = 0x32,
  BapFct_SeatBF_Massage_2 = 0x33,
  BapFct_SeatBF_4DSound = 0x34,
  BapFct_SeatBF_VisualisationConfig3 = 0x35,
  BapFct_SeatBF_VisualisationConfig4DSound = 0x36,
  /* Steuergeraet VZA */
  BapFct_VZA_GetAll = 0x01,
  BapFct_VZA_BAP_Config = 0x02,
  BapFct_VZA_FunctionList = 0x03,
  BapFct_VZA_Heartbeat = 0x04,
  BapFct_VZA_FSG_Control = 0x0d,
  BapFct_VZA_FSG_Setup = 0x0e,
  BapFct_VZA_FSG_OperationState = 0x0f,
  BapFct_VZA_RoadSign = 0x10,
  BapFct_VZA_RoadSignFilter = 0x11,
  BapFct_VZA_Trailermode = 0x12,
  BapFct_VZA_SystemMessages = 0x13,
  BapFct_VZA_SpeedWarnThreshold = 0x14,
  BapFct_VZA_TrailerSpeedLimit = 0x15,
  BapFct_VZA_SpeedWarnAcoustics = 0x16,
  BapFct_VZA_RoadSign2 = 0x17,
  BapFct_VZA_PSO_ImExport = 0x18,
  BapFct_VZA_SpeedLimitNotifications = 0x19,
  BapFct_VZA_SpeedChangeAcoustics = 0x1a,
  BapFct_VZA_SpeedWarnOverruled = 0x1b,
  BapFct_VZA_TrailerSpeedLimitValues = 0x1c,
  BapFct_VZA_SpeedWarningThresholdValues = 0x1d,
  BapFct_VZA_TrafficLightDisplay = 0x1e,
  BapFct_VZA_TrafficLightWarning = 0x1f,
  BapFct_VZA_StopSignDisplay = 0x20,
  BapFct_VZA_StopSignWarning = 0x21,
  BapFct_VZA_SystemMessages2 = 0x22,
  BapFct_VZA_SignAssist_LM = 0x23,
  BapFct_VZA_TrafficLightDepartureAssist = 0x24,
  BapFct_VZA_TrafficLightWarningSensitivity = 0x25,
  BapFct_VZA_StopSignWarningSensitivity = 0x26,
  BapFct_VZA_TLDA_Sensitivity = 0x27,
  BapFct_VZA_StopLine = 0x28,
  /* Steuergeraet MKE */
  BapFct_MKE_GetAll = 0x01,
  BapFct_MKE_BAP_Config = 0x02,
  BapFct_MKE_FunctionList = 0x03,
  BapFct_MKE_Heartbeat = 0x04,
  BapFct_MKE_FSG_Control = 0x0d,
  BapFct_MKE_FSG_OperationState = 0x0f,
  BapFct_MKE_Message = 0x10,
  BapFct_MKE_RestAreaRecommendation = 0x11,
  BapFct_MKE_DrivingTime = 0x12,
  BapFct_MKE_MKE_Setup = 0x13,
  BapFct_MKE_ALE_Setup = 0x14,
  BapFct_MKE_Stringency = 0x15,
  BapFct_MKE_FSG_Setup = 0x16,
  BapFct_MKE_MKE_Setup_LM = 0x17,
  BapFct_MKE_ALE_Setup_LM = 0x18,
  /* Steuergeraet BCmE */
  BapFct_BCmE_GetAll = 0x01,
  BapFct_BCmE_BAP_Config = 0x02,
  BapFct_BCmE_FunctionList = 0x03,
  BapFct_BCmE_HeartBeat = 0x04,
  BapFct_BCmE_FSG_Control = 0x0d,
  BapFct_BCmE_FSG_Setup = 0x0e,
  BapFct_BCmE_FSG_OperationState = 0x0f,
  BapFct_BCmE_Consumer = 0x10,
  BapFct_BCmE_Consumption = 0x11,
  BapFct_BCmE_LiveTip = 0x12,
  BapFct_BCmE_EnergyFlowComfort = 0x13,
  BapFct_BCmE_RangeGainTotal = 0x14,
  BapFct_BCmE_ConsumerListConsumption = 0x15,
  BapFct_BCmE_ConsumerListRange = 0x16,
  BapFct_BCmE_CurrentRange = 0x17,
  BapFct_BCmE_CurrentRangeSOC = 0x18,
  BapFct_BCmE_CatalogueRange = 0x19,
  /* Steuergeraet BatteryControl */
  BapFct_BatteryControl_GetAll = 0x01,
  BapFct_BatteryControl_BAP_Config = 0x02,
  BapFct_BatteryControl_FunctionList = 0x03,
  BapFct_BatteryControl_HeartBeat = 0x04,
  BapFct_BatteryControl_FSG_Control = 0x0d,
  BapFct_BatteryControl_FSG_Setup = 0x0e,
  BapFct_BatteryControl_FSG_OperationState = 0x0f,
  BapFct_BatteryControl_Global_TargetSoc = 0x10,
  BapFct_BatteryControl_Global_TargetRange = 0x11,
  BapFct_BatteryControl_Global_MaxCurrentAc = 0x12,
  BapFct_BatteryControl_Global_Autounlock = 0x13,
  BapFct_BatteryControl_Global_ItPeRange = 0x14,
  BapFct_BatteryControl_NavTargetSoc = 0x15,
  BapFct_BatteryControl_ChargeModeSelection = 0x16,
  BapFct_BatteryControl_ChargingProcessInfo = 0x17,
  BapFct_BatteryControl_ChargingTimes = 0x18,
  BapFct_BatteryControl_ChargingPlug1 = 0x19,
  BapFct_BatteryControl_ChargingPlug2 = 0x1a,
  BapFct_BatteryControl_ImmediateActions = 0x1b,
  BapFct_BatteryControl_NotificationMarkers = 0x1c,
  BapFct_BatteryControl_Notifications = 0x1d,
  BapFct_BatteryControl_PastErrorInformation = 0x1e,
  BapFct_BatteryControl_Views = 0x1f,
  BapFct_BatteryControl_ProfileStatus = 0x20,
  BapFct_BatteryControl_ChargingProfiles = 0x21,
  BapFct_BatteryControl_ChargingTimers = 0x22,
  BapFct_BatteryControl_NextChargingTimer = 0x23,
  BapFct_BatteryControl_PreferredChargingTimes = 0x24,
  BapFct_BatteryControl_EVSEID = 0x25,
  BapFct_BatteryControl_HighLevelCommunication = 0x26,
  BapFct_BatteryControl_Contracts = 0x27,
  BapFct_BatteryControl_BatteryChargingCareMode = 0x28,
  BapFct_BatteryControl_UBE_Data = 0x29,
  /* Steuergeraet Brake */
  BapFct_Brake_GetAll = 0x01,
  BapFct_Brake_BAP_Config = 0x02,
  BapFct_Brake_FunctionList = 0x03,
  BapFct_Brake_HeartBeat = 0x04,
  BapFct_Brake_FSG_Control = 0x0d,
  BapFct_Brake_FSG_Setup = 0x0e,
  BapFct_Brake_FSG_OperationState = 0x0f,
  BapFct_Brake_ElectricalParkingBrake = 0x10,
  BapFct_Brake_AutoHold = 0x11,
  BapFct_Brake_ESC_Mode = 0x12,
  BapFct_Brake_HDC_Mode = 0x13,
  BapFct_Brake_Popup = 0x14,
  BapFct_Brake_BrakeRefreshActivation = 0x15,
  BapFct_Brake_BrakeBeddingStatus = 0x16,
  BapFct_Brake_ESC_Mode2 = 0x17,
  /* Steuergeraet Telephone */
  BapFct_Telephone_GetAll = 0x01,
  BapFct_Telephone_BAP_Config = 0x02,
  BapFct_Telephone_FunctionList = 0x03,
  BapFct_Telephone_HeartBeat = 0x04,
  BapFct_Telephone_FSG_Control = 0x0d,
  BapFct_Telephone_FSG_Setup = 0x0e,
  BapFct_Telephone_FSG_OperationState = 0x0f,
  BapFct_Telephone_MobileServiceSupport = 0x10,
  BapFct_Telephone_DeviceConnectionState = 0x11,
  BapFct_Telephone_NetworkState = 0x12,
  BapFct_Telephone_NetworkProvider = 0x13,
  BapFct_Telephone_ActiveUser = 0x14,
  BapFct_Telephone_MobileBatteryLevel = 0x15,
  BapFct_Telephone_CallState = 0x16,
  BapFct_Telephone_CallInfo = 0x17,
  BapFct_Telephone_CallDuration = 0x18,
  BapFct_Telephone_AudioMuteOnOff = 0x19,
  BapFct_Telephone_MissedCallIndication = 0x1a,
  BapFct_Telephone_AutomaticRedial = 0x1b,
  BapFct_Telephone_DialNumber = 0x1c,
  BapFct_Telephone_ConfirmEmergencyCall = 0x1d,
  BapFct_Telephone_BasicCallHandling = 0x1e,
  BapFct_Telephone_MPCall_CC_Handling = 0x1f,
  BapFct_Telephone_CombinedNumbers = 0x20,
  BapFct_Telephone_Picture = 0x21,
  BapFct_Telephone_AudioSink = 0x22,
  BapFct_Telephone_ActiveUserSecondaryPhone = 0x23,
  /* Steuergeraet OnlineFunctions_SD */
  BapFct_OnlineFunctions_SD_GetAll = 0x01,
  BapFct_OnlineFunctions_SD_BAP_Config = 0x02,
  BapFct_OnlineFunctions_SD_FunctionList = 0x03,
  BapFct_OnlineFunctions_SD_Heartbeat = 0x04,
  BapFct_OnlineFunctions_SD_FSG_Control = 0x0d,
  BapFct_OnlineFunctions_SD_FSG_Setup = 0x0e,
  BapFct_OnlineFunctions_SD_FSG_OperationState = 0x0f,
  BapFct_OnlineFunctions_SD_TrafficLightOnline_Info = 0x10,
  BapFct_OnlineFunctions_SD_TrafficLightOnline_Speed = 0x11,
  BapFct_OnlineFunctions_SD_TrafficLightOnline_Time = 0x12,
  BapFct_OnlineFunctions_SD_OnlineServiceSupport = 0x13,
  /* Steuergeraet Audio_SD */
  BapFct_Audio_SD_GetAll = 0x01,
  BapFct_Audio_SD_BAP_Config = 0x02,
  BapFct_Audio_SD_FunctionList = 0x03,
  BapFct_Audio_SD_HeartBeat = 0x04,
  BapFct_Audio_SD_FSG_Control = 0x0d,
  BapFct_Audio_SD_FSG_Setup = 0x0e,
  BapFct_Audio_SD_FSG_OperationState = 0x0f,
  BapFct_Audio_SD_ASG_Capabilities = 0x10,
  BapFct_Audio_SD_InfoStates = 0x11,
  BapFct_Audio_SD_SDS_State = 0x12,
  BapFct_Audio_SD_GeneralInfoSwitches = 0x13,
  BapFct_Audio_SD_ActiveSource = 0x14,
  BapFct_Audio_SD_ActiveSourceName = 0x15,
  BapFct_Audio_SD_CurrentVolume = 0x16,
  BapFct_Audio_SD_SourceState = 0x17,
  BapFct_Audio_SD_CurrentStationInfo = 0x18,
  BapFct_Audio_SD_CurrentStation_Handle = 0x19,
  BapFct_Audio_SD_PlayPosition = 0x1a,
  BapFct_Audio_SD_Station_Track_Switch = 0x1b,
  BapFct_Audio_SD_AnnouncementInfo = 0x1c,
  BapFct_Audio_SD_AnnouncementEscape = 0x1d,
  BapFct_Audio_SD_ReceptionList = 0x1e,
  BapFct_Audio_SD_RadioTV_PresetList = 0x1f,
  BapFct_Audio_SD_ListSetup = 0x20,
  BapFct_Audio_SD_SourceList = 0x21,
  BapFct_Audio_SD_DedicatedAudioControl = 0x22,
  BapFct_Audio_SD_SwitchSource = 0x23,
  BapFct_Audio_SD_Browser_FolderLevel = 0x24,
  BapFct_Audio_SD_Browser = 0x25,
  BapFct_Audio_SD_BrowserPath = 0x26,
  BapFct_Audio_SD_BrowserControl = 0x27,
  BapFct_Audio_SD_Picture = 0x28,
  BapFct_Audio_SD_FunctionSynchronisation = 0x29,
  BapFct_Audio_SD_InfoText = 0x2a,
  /* Steuergeraet Navigation_SD */
  BapFct_Navigation_SD_GetAll = 0x01,
  BapFct_Navigation_SD_BAP_Config = 0x02,
  BapFct_Navigation_SD_FunctionList = 0x03,
  BapFct_Navigation_SD_HeartBeat = 0x04,
  BapFct_Navigation_SD_FSG_Control = 0x0d,
  BapFct_Navigation_SD_FSG_Setup = 0x0e,
  BapFct_Navigation_SD_FSG_OperationState = 0x0f,
  BapFct_Navigation_SD_InfoStates = 0x10,
  BapFct_Navigation_SD_ActiveRgType = 0x11,
  BapFct_Navigation_SD_CompassInfo = 0x12,
  BapFct_Navigation_SD_RG_State = 0x13,
  BapFct_Navigation_SD_DistanceToNextManeuver = 0x14,
  BapFct_Navigation_SD_CurrentPositionInfo = 0x15,
  BapFct_Navigation_SD_Altitude = 0x16,
  BapFct_Navigation_SD_TurnToInfo = 0x17,
  BapFct_Navigation_SD_DistTimeToDestination = 0x18,
  BapFct_Navigation_SD_ManeuverDescriptor_1 = 0x19,
  BapFct_Navigation_SD_ManeuverDescriptor_2 = 0x1a,
  BapFct_Navigation_SD_ManeuverDescriptor_3 = 0x1b,
  BapFct_Navigation_SD_LaneGuidance = 0x1c,
  BapFct_Navigation_SD_TMCinfo = 0x1d,
  BapFct_Navigation_SD_LastDest_List = 0x1e,
  BapFct_Navigation_SD_FavoriteDest_List = 0x1f,
  BapFct_Navigation_SD_ListSetup = 0x20,
  BapFct_Navigation_SD_RG_ActDeact = 0x21,
  BapFct_Navigation_SD_RptLastNavAnnouncement = 0x22,
  BapFct_Navigation_SD_MapScale = 0x23,
  BapFct_Navigation_SD_VideoStreams = 0x24,
  BapFct_Navigation_SD_RequestSync_Video = 0x25,
  BapFct_Navigation_SD_Picture = 0x26,
  BapFct_Navigation_SD_ChargingStates = 0x27,
  BapFct_Navigation_SD_FunctionSynchronisation = 0x28,
  BapFct_Navigation_SD_DestinationInfo = 0x29,
  BapFct_Navigation_SD_LHWinfo = 0x2a,
  BapFct_Navigation_SD_NavigationInformation = 0x2b,
  /* Steuergeraet eCall */
  BapFct_eCall_GetAll = 0x01,
  BapFct_eCall_BAP_Config = 0x02,
  BapFct_eCall_FunctionList = 0x03,
  BapFct_eCall_HeartBeat = 0x04,
  BapFct_eCall_FSG_Control = 0x0d,
  BapFct_eCall_FSG_Setup = 0x0e,
  BapFct_eCall_FSG_OperationState = 0x0f,
  BapFct_eCall_AudioState = 0x10,
  BapFct_eCall_CallState = 0x11,
  BapFct_eCall_HangupCall = 0x12,
  BapFct_eCall_AcceptCall = 0x13,
  BapFct_eCall_DisconnectReason = 0x14,
  BapFct_eCall_RegisterState = 0x15,
  BapFct_eCall_NetworkProvider = 0x16,
  BapFct_eCall_SignalQuality = 0x17,
  BapFct_eCall_ServiceRequest = 0x18,
  BapFct_eCall_ServiceControl = 0x19,
  BapFct_eCall_ServiceState = 0x1a,
  BapFct_eCall_SupportedServices = 0x1b,
  BapFct_eCall_FunctionalRestrictions = 0x1c,
  BapFct_eCall_AllowedEmergencyNumbers = 0x1d,
  BapFct_eCall_DialNumber = 0x1e,
  BapFct_eCall_DisasterWarning = 0x1f,
  BapFct_eCall_AdditionalCallbackNumbers = 0x20,
  BapFct_eCall_DialNumberCallType = 0x21,
  BapFct_eCall_DTMFTonePlaying = 0x22,
  /* Steuergeraet MFL_Config */
  BapFct_MFL_Config_GetAll = 0x01,
  BapFct_MFL_Config_BAP_Config = 0x02,
  BapFct_MFL_Config_FunctionList = 0x03,
  BapFct_MFL_Config_HeartBeat = 0x04,
  BapFct_MFL_Config_FSG_Setup = 0x0e,
  BapFct_MFL_Config_FSG_OperationState = 0x0f,
  BapFct_MFL_Config_InstrumentClusterFunctions = 0x10,
  BapFct_MFL_Config_KeyConfiguration = 0x11,
  BapFct_MFL_Config_KeyAction = 0x12,
  BapFct_MFL_Config_PU_Content = 0x13,
  BapFct_MFL_Config_PU_Action = 0x14,
  /* Steuergeraet TrailerAssist */
  BapFct_TrailerAssist_GetAll = 0x01,
  BapFct_TrailerAssist_BAP_Config = 0x02,
  BapFct_TrailerAssist_FunctionList = 0x03,
  BapFct_TrailerAssist_HeartBeat = 0x04,
  BapFct_TrailerAssist_FSG_Control = 0x0d,
  BapFct_TrailerAssist_FSG_Setup = 0x0e,
  BapFct_TrailerAssist_FSG_OperationState = 0x0f,
  BapFct_TrailerAssist_TrailerConfig = 0x10,
  BapFct_TrailerAssist_CurrentTrailerAngle = 0x11,
  BapFct_TrailerAssist_TargetTrailerAngle = 0x12,
  BapFct_TrailerAssist_Info = 0x13,
  BapFct_TrailerAssist_Display = 0x14,
  BapFct_TrailerAssist_SystemState = 0x15,
  BapFct_TrailerAssist_RemoteARA_SystemState = 0x16,
  BapFct_TrailerAssist_RemoteARA_Info = 0x17,
  BapFct_TrailerAssist_ARAMode = 0x18,
  /* Steuergeraet ENI */
  BapFct_ENI_GetAll = 0x01,
  BapFct_ENI_BAP_Config = 0x02,
  BapFct_ENI_FunctionList = 0x03,
  BapFct_ENI_HeartBeat = 0x04,
  BapFct_ENI_FSG_Control = 0x0d,
  BapFct_ENI_FSG_Setup = 0x0e,
  BapFct_ENI_FSG_OperationState = 0x0f,
  BapFct_ENI_DestinationsList = 0x10,
  BapFct_ENI_DestinationList_ASGcapacity = 0x11,
  BapFct_ENI_TriggerRemoteProcess = 0x12,
  BapFct_ENI_RemoteProcessCommands = 0x13,
  BapFct_ENI_RemoteProcessState = 0x14,
  BapFct_ENI_UserList = 0x15,
  BapFct_ENI_ServiceList = 0x16,
  BapFct_ENI_ActiveMonitorings = 0x17,
  BapFct_ENI_PrivacySetup = 0x18,
  BapFct_ENI_AlertList = 0x19,
  BapFct_ENI_MobileDeviceKeyCount = 0x1a,
  BapFct_ENI_VTANDataEncrypted = 0x1b,
  BapFct_ENI_ConnectionState = 0x1d,
  BapFct_ENI_ChallengeData = 0x1e,
  BapFct_ENI_FoDList = 0x1f,
  BapFct_ENI_FoDState = 0x20,
  BapFct_ENI_ActiveTrip = 0x21,
  BapFct_ENI_OLBSettings = 0x22,
  BapFct_ENI_OLBTripList = 0x23,
  BapFct_ENI_CurrentOnlineUpdateState = 0x24,
  BapFct_ENI_OnlineUpdateList = 0x25,
  BapFct_ENI_PrivacyGroupSetup = 0x26,
  BapFct_ENI_FoD_M_FECList = 0x27,
  BapFct_ENI_MobDevPairing = 0x28,
  BapFct_ENI_OperationsList = 0x29,
  BapFct_ENI_WlanState = 0x2a,
  BapFct_ENI_WlanConfiguration = 0x2b,
  BapFct_ENI_FoD_SyncState = 0x2c,
  BapFct_ENI_FoD_BaseReportList = 0x2d,
  BapFct_ENI_FoD_FunctionReportList = 0x2e,
  /* Steuergeraet RangeData */
  BapFct_RangeData_GetAll = 0x01,
  BapFct_RangeData_BAP_Config = 0x02,
  BapFct_RangeData_Fct_List = 0x03,
  BapFct_RangeData_Heartbeat = 0x04,
  BapFct_RangeData_FSG_Control = 0x0d,
  BapFct_RangeData_FSG_Setup = 0x0e,
  BapFct_RangeData_FSG_OperationState = 0x0f,
  BapFct_RangeData_MaxRange = 0x10,
  BapFct_RangeData_ResidualEnergy = 0x11,
  BapFct_RangeData_Consumption_Motorway = 0x12,
  BapFct_RangeData_Consumption_Highway = 0x13,
  BapFct_RangeData_Consumption_CountryRoad = 0x14,
  BapFct_RangeData_Consumption_DistrictRoad = 0x15,
  BapFct_RangeData_Consumption_LocalRoad = 0x16,
  BapFct_RangeData_Consumption_RuralRoad = 0x17,
  BapFct_RangeData_Consumption_UnclassifiedRoad = 0x18,
  BapFct_RangeData_FSG_Setup2 = 0x19,
  BapFct_RangeData_Consumption_SpeedRelated_CurrentMode = 0x1a,
  BapFct_RangeData_Consumption_SpeedRelated_NormalMode = 0x1b,
  BapFct_RangeData_Consumption_SpeedRelated_Efficiency1 = 0x1c,
  BapFct_RangeData_Consumption_SpeedRelated_Efficiency2 = 0x1d,
  BapFct_RangeData_Consumption_AdditionalConsumers_CurrentMode = 0x1e,
  BapFct_RangeData_Consumption_AdditionalConsumers_NormalMode = 0x1f,
  BapFct_RangeData_Consumption_AdditionalConsumers_Efficiency1 = 0x20,
  BapFct_RangeData_Consumption_AdditionalConsumers_Efficiency2 = 0x21,
  BapFct_RangeData_GradeConsumption = 0x22,
  BapFct_RangeData_EnergyRange = 0x23,
  BapFct_RangeData_CurrentRange = 0x24,
  BapFct_RangeData_CurrentRange_rRWB = 0x25,
  BapFct_RangeData_CalculatedRange = 0x26,
  BapFct_RangeData_TargetSOC_Charging = 0x27,
  /* Steuergeraet SeatPneumatic */
  BapFct_SeatPneumatic_GetAll = 0x01,
  BapFct_SeatPneumatic_BAP_Config = 0x02,
  BapFct_SeatPneumatic_FunctionList = 0x03,
  BapFct_SeatPneumatic_HeartBeat = 0x04,
  BapFct_SeatPneumatic_FSG_Control = 0x0d,
  BapFct_SeatPneumatic_FSG_Setup = 0x0e,
  BapFct_SeatPneumatic_FSG_OperationState = 0x0f,
  BapFct_SeatPneumatic_VisualisationConfig_Front = 0x10,
  BapFct_SeatPneumatic_CodriverSettingsFromDriver = 0x11,
  BapFct_SeatPneumatic_Seat_FrontLeft_Display = 0x12,
  BapFct_SeatPneumatic_Seat_FrontLeft_Massage = 0x13,
  BapFct_SeatPneumatic_Seat_FrontLeft_Switch = 0x14,
  BapFct_SeatPneumatic_Seat_FrontRight_Display = 0x15,
  BapFct_SeatPneumatic_Seat_FrontRight_Massage = 0x16,
  BapFct_SeatPneumatic_Seat_FrontRight_Switch = 0x17,
  BapFct_SeatPneumatic_FL_MassageSwitch = 0x18,
  BapFct_SeatPneumatic_FR_MassageSwitch = 0x19,
  BapFct_SeatPneumatic_PSO_ImExport = 0x1a,
  BapFct_SeatPneumatic_FL_MassageProgramList = 0x1b,
  BapFct_SeatPneumatic_FR_MassageProgramList = 0x1c,
  BapFct_SeatPneumatic_Seat_FL_Massage_Ext = 0x1d,
  BapFct_SeatPneumatic_Seat_FR_Massage_Ext = 0x1e,
  /* Steuergeraet EfficiencyAssist */
  BapFct_EfficiencyAssist_GetAll = 0x01,
  BapFct_EfficiencyAssist_BAP_Config = 0x02,
  BapFct_EfficiencyAssist_FunctionList = 0x03,
  BapFct_EfficiencyAssist_HeartBeat = 0x04,
  BapFct_EfficiencyAssist_FSG_Control = 0x0d,
  BapFct_EfficiencyAssist_FSG_Setup = 0x0e,
  BapFct_EfficiencyAssist_FSG_OperationState = 0x0f,
  BapFct_EfficiencyAssist_PedalJerk = 0x10,
  BapFct_EfficiencyAssist_DriverEvent = 0x11,
  BapFct_EfficiencyAssist_DistanceToEvent = 0x12,
  BapFct_EfficiencyAssist_DriverAction = 0x13,
  BapFct_EfficiencyAssist_ActionFeedback = 0x14,
  BapFct_EfficiencyAssist_Messages = 0x15,
  BapFct_EfficiencyAssist_FreeWheeling = 0x16,
  BapFct_EfficiencyAssist_StartStop = 0x17,
  BapFct_EfficiencyAssist_IntelligentRecuperation = 0x18,
  BapFct_EfficiencyAssist_PredictiveHints = 0x19,
  BapFct_EfficiencyAssist_PSO_ImExport = 0x1a,
  BapFct_EfficiencyAssist_StartStop_LM = 0x1b,
  BapFct_EfficiencyAssist_Mainswitch = 0x1c,
  BapFct_EfficiencyAssist_RecuEveSpdLimit = 0x1d,
  BapFct_EfficiencyAssist_RecuEveRoad = 0x1e,
  BapFct_EfficiencyAssist_RecuEveStop = 0x1f,
  BapFct_EfficiencyAssist_RecuDecent = 0x20,
  BapFct_EfficiencyAssist_VehDistanceCtrl = 0x21,
  BapFct_EfficiencyAssist_IntRecu_DrvMod_B = 0x22,
  /* Steuergeraet ClimateMaster */
  BapFct_ClimateMaster_GetAll = 0x01,
  BapFct_ClimateMaster_BAP_Config = 0x02,
  BapFct_ClimateMaster_FunctionList = 0x03,
  BapFct_ClimateMaster_HeartBeat = 0x04,
  BapFct_ClimateMaster_FSG_Control = 0x0d,
  BapFct_ClimateMaster_FSG_Setup = 0x0e,
  BapFct_ClimateMaster_FSG_OperationState = 0x0f,
  BapFct_ClimateMaster_AC = 0x10,
  BapFct_ClimateMaster_AirCirculation = 0x11,
  BapFct_ClimateMaster_AutomaticAirCirculation = 0x12,
  BapFct_ClimateMaster_Solar = 0x13,
  BapFct_ClimateMaster_IndirectVentilation = 0x14,
  BapFct_ClimateMaster_Synchronisation = 0x15,
  BapFct_ClimateMaster_PopupContent = 0x16,
  BapFct_ClimateMaster_DP_Presentation = 0x17,
  BapFct_ClimateMaster_FrontWindowHeater = 0x18,
  BapFct_ClimateMaster_RearWindowHeater = 0x19,
  BapFct_ClimateMaster_SteeringwheelHeater = 0x1a,
  BapFct_ClimateMaster_AuxHeater = 0x1b,
  BapFct_ClimateMaster_RearAuxHeater = 0x1c,
  BapFct_ClimateMaster_ResidualHeat = 0x1d,
  BapFct_ClimateMaster_Defrost = 0x1e,
  BapFct_ClimateMaster_RearControlLock = 0x1f,
  BapFct_ClimateMaster_RearPriorisation = 0x20,
  BapFct_ClimateMaster_BlowerCompensation = 0x21,
  BapFct_ClimateMaster_AirQuality = 0x22,
  BapFct_ClimateMaster_FreshAirConfiguration = 0x23,
  BapFct_ClimateMaster_FreshAirState = 0x24,
  BapFct_ClimateMaster_PureAir = 0x25,
  BapFct_ClimateMaster_AirQuality_2 = 0x26,
  BapFct_ClimateMaster_BehaviorMode = 0x27,
  BapFct_ClimateMaster_PSO_ImExport = 0x28,
  BapFct_ClimateMaster_ECOModeControl = 0x29,
  BapFct_ClimateMaster_VoiceControl = 0x2a,
  BapFct_ClimateMaster_Learning = 0x2b,
  BapFct_ClimateMaster_WinterFunction = 0x2c,
  BapFct_ClimateMaster_FANOnlyMode = 0x2d,
  BapFct_ClimateMaster_SeatClimateSynchronisation = 0x2e,
  BapFct_ClimateMaster_FSG_Setup2 = 0x2f,
  BapFct_ClimateMaster_CabinScene = 0x30,
  BapFct_ClimateMaster_FreshAirState2 = 0x31,
  BapFct_ClimateMaster_ParticleChargingUnit = 0x32,
  BapFct_ClimateMaster_PremiumAirQuality = 0x33,
  BapFct_ClimateMaster_RearControlLock_SR3 = 0x34,
  BapFct_ClimateMaster_GenericSceneConfig = 0x35,
  /* Steuergeraet DisplayConfig */
  BapFct_DisplayConfig_GetAll = 0x01,
  BapFct_DisplayConfig_BAP_Config = 0x02,
  BapFct_DisplayConfig_FunctionList = 0x03,
  BapFct_DisplayConfig_HeartBeat = 0x04,
  BapFct_DisplayConfig_FSG_Control = 0x0d,
  BapFct_DisplayConfig_FSG_Setup = 0x0e,
  BapFct_DisplayConfig_FSG_OperationState = 0x0f,
  BapFct_DisplayConfig_Brightness = 0x10,
  BapFct_DisplayConfig_Volume = 0x11,
  BapFct_DisplayConfig_ElementContentSelection = 0x12,
  BapFct_DisplayConfig_Display1Setup = 0x13,
  BapFct_DisplayConfig_Display1MainSelection = 0x14,
  BapFct_DisplayConfig_Display2Setup = 0x15,
  BapFct_DisplayConfig_Display2MainSelection = 0x16,
  BapFct_DisplayConfig_Display3Setup = 0x17,
  BapFct_DisplayConfig_Display3MainSelection = 0x18,
  BapFct_DisplayConfig_AdditionalInstrument = 0x19,
  BapFct_DisplayConfig_AdditionalInstrument2 = 0x1a,
  BapFct_DisplayConfig_DisplayPresets = 0x1b,
  BapFct_DisplayConfig_DisplayDependency = 0x1c,
  BapFct_DisplayConfig_ActiveDisplayPreset = 0x1d,
  BapFct_DisplayConfig_DisplayViewConfiguration = 0x1e,
  BapFct_DisplayConfig_LED_Configuration = 0x1f,
  BapFct_DisplayConfig_PopupSelection = 0x20,
  BapFct_DisplayConfig_AutoSkinSwitch = 0x21,
  BapFct_DisplayConfig_PSO_ImExport = 0x22,
  BapFct_DisplayConfig_DrivingProfileSkinSwitch = 0x23,
  /* Steuergeraet SDS_SD */
  BapFct_SDS_SD_GetAll = 0x01,
  BapFct_SDS_SD_BAP_Config = 0x02,
  BapFct_SDS_SD_FunctionList = 0x03,
  BapFct_SDS_SD_Heartbeat = 0x04,
  BapFct_SDS_SD_FSG_Setup = 0x0e,
  BapFct_SDS_SD_FSG_OperationState = 0x0f,
  BapFct_SDS_SD_ASG_Capabilities = 0x10,
  BapFct_SDS_SD_SDS_ContextState = 0x11,
  BapFct_SDS_SD_CommandList = 0x12,
  BapFct_SDS_SD_ResultList = 0x13,
  BapFct_SDS_SD_InfoStates = 0x14,
  BapFct_SDS_SD_DedicatedSpeechControl = 0x15,
  BapFct_SDS_SD_SDS_RecognizerState = 0x16,
  BapFct_SDS_SD_SDS_DialogState = 0x17,
  BapFct_SDS_SD_SDS_OnlineState = 0x18,
  BapFct_SDS_SD_ChatList = 0x19,
  BapFct_SDS_SD_Picture = 0x1a,
  /* Steuergeraet Statistics */
  BapFct_Statistics_GetAll = 0x01,
  BapFct_Statistics_BAP_Config = 0x02,
  BapFct_Statistics_FunctionList = 0x03,
  BapFct_Statistics_HeartBeat = 0x04,
  BapFct_Statistics_FSG_Control = 0x0d,
  BapFct_Statistics_FSG_Setup = 0x0e,
  BapFct_Statistics_FSG_OperationState = 0x0f,
  BapFct_Statistics_TimeBased_ConsumptionData = 0x10,
  BapFct_Statistics_TimeBased_DrivingModes = 0x11,
  BapFct_Statistics_CurrentIntervall_DrivingModes = 0x12,
  BapFct_Statistics_DistanceBased_DrivingModes_KM = 0x13,
  BapFct_Statistics_DistanceBased_DrivingModes_MLS = 0x14,
  BapFct_Statistics_DistanceBased_DrivingModes_Accumulated = 0x15,
  BapFct_Statistics_ResetIndicator = 0x16,
  BapFct_Statistics_Reset = 0x17,
  BapFct_Statistics_DistanceBased_ConsumptStat = 0x18,
  BapFct_Statistics_ResetIndicator_ConsumptStat = 0x19,
  BapFct_Statistics_Reset_ConsumptStatist = 0x1a,
  /* Steuergeraet Sunroof */
  BapFct_Sunroof_GetAll = 0x01,
  BapFct_Sunroof_BAP_Config = 0x02,
  BapFct_Sunroof_FunctionList = 0x03,
  BapFct_Sunroof_HeartBeat = 0x04,
  BapFct_Sunroof_FSG_Control = 0x0d,
  BapFct_Sunroof_FSG_Setup = 0x0e,
  BapFct_Sunroof_FSG_OperationState = 0x0f,
  BapFct_Sunroof_SunroofSliding = 0x10,
  BapFct_Sunroof_SunroofTilt = 0x11,
  BapFct_Sunroof_RoofBlind = 0x12,
  BapFct_Sunroof_SunroofState = 0x13,
  BapFct_Sunroof_RoofBlindState = 0x14,
  BapFct_Sunroof_GlassRoofSliding = 0x15,
  BapFct_Sunroof_GlassRoofDimming = 0x16,
  BapFct_Sunroof_GlassRoofOnOff = 0x17,
  BapFct_Sunroof_GlassRoofPresets = 0x18,
  BapFct_Sunroof_GlassRoofSegControl = 0x19,
  BapFct_Sunroof_GlassRoofAnimationDirection = 0x1a,
  BapFct_Sunroof_Display = 0x1b,
  /* Steuergeraet FAS_Profiles */
  BapFct_FAS_Profiles_GetAll = 0x01,
  BapFct_FAS_Profiles_BAP_Config = 0x02,
  BapFct_FAS_Profiles_FunctionList = 0x03,
  BapFct_FAS_Profiles_HeartBeat = 0x04,
  BapFct_FAS_Profiles_FSG_Control = 0x0d,
  BapFct_FAS_Profiles_FSG_Setup = 0x0e,
  BapFct_FAS_Profiles_FSG_OperationState = 0x0f,
  BapFct_FAS_Profiles_FAS_ProfileConfiguration = 0x10,
  BapFct_FAS_Profiles_SetupProfile = 0x11,
  BapFct_FAS_Profiles_Display = 0x12,
  BapFct_FAS_Profiles_Messages = 0x13,
  /* Steuergeraet InfoSettings */
  BapFct_InfoSettings_GetAll = 0x01,
  BapFct_InfoSettings_BAP_Config = 0x02,
  BapFct_InfoSettings_FunctionList = 0x03,
  BapFct_InfoSettings_HeartBeat = 0x04,
  BapFct_InfoSettings_FSG_Control = 0x0d,
  BapFct_InfoSettings_FSG_Setup = 0x0e,
  BapFct_InfoSettings_FSG_OperationState = 0x0f,
  BapFct_InfoSettings_ResetFactorySettings = 0x10,
  BapFct_InfoSettings_ToneVolume = 0x11,
  BapFct_InfoSettings_ToneSettings = 0x12,
  BapFct_InfoSettings_SoundSettings = 0x13,
  BapFct_InfoSettings_RadioFavoriteCommands = 0x14,
  BapFct_InfoSettings_BTPairingState = 0x15,
  BapFct_InfoSettings_BTDeviceList = 0x16,
  BapFct_InfoSettings_BTPairingCommands = 0x17,
  BapFct_InfoSettings_LicenseInformation = 0x18,
  BapFct_InfoSettings_VersionInfo = 0x19,
  BapFct_InfoSettings_UpdateState = 0x1a,
  BapFct_InfoSettings_UpdateCommands = 0x1b,
  BapFct_InfoSettings_PSO_ImExport = 0x1c,
  BapFct_InfoSettings_FocusSwitch = 0x1d,
  BapFct_InfoSettings_ActiveAppInformation = 0x1e,
  BapFct_InfoSettings_DisplayArea = 0x1f,
  BapFct_InfoSettings_DisplaySettings = 0x20,
  BapFct_InfoSettings_Picture = 0x21,
  BapFct_InfoSettings_IAA_State = 0x22,
  BapFct_InfoSettings_EgoVehicleColor = 0x23,
  /* Steuergeraet PaCo */
  BapFct_PaCo_GetAll = 0x01,
  BapFct_PaCo_BAP_Config = 0x02,
  BapFct_PaCo_FunctionList = 0x03,
  BapFct_PaCo_Heartbeat = 0x04,
  BapFct_PaCo_FSG_Control = 0x0d,
  BapFct_PaCo_FSG_Setup = 0x0e,
  BapFct_PaCo_FSG_OperationState = 0x0f,
  BapFct_PaCo_SystemState = 0x10,
  BapFct_PaCo_FeatureStateVPS = 0x11,
  BapFct_PaCo_FeatureStateParking = 0x12,
  BapFct_PaCo_ViewRequest = 0x13,
  BapFct_PaCo_ViewAvailability = 0x14,
  BapFct_PaCo_ViewSwitch = 0x15,
  BapFct_PaCo_ViewState = 0x16,
  BapFct_PaCo_ParkingIndications = 0x17,
  BapFct_PaCo_LifeMonitoring = 0x18,
  BapFct_PaCo_IC_Messages = 0x19,
  BapFct_PaCo_FavoriteList = 0x1a,
  BapFct_PaCo_PSO_ImExport = 0x1b,
  BapFct_PaCo_SystemState2 = 0x1c,
  BapFct_PaCo_ShowMessage = 0x1d,
  BapFct_PaCo_ParkingIndications2 = 0x1e,
  BapFct_PaCo_IPA_AutoActivation = 0x1f,
  BapFct_PaCo_MM_Messages_CD = 0x20,
  BapFct_PaCo_FeatureStateParking2 = 0x21,
  BapFct_PaCo_FeatureStateParking_RCTA_LM = 0x22,
  /* Steuergeraet ENI2 */
  BapFct_ENI2_GetAll = 0x01,
  BapFct_ENI2_BAP_Config = 0x02,
  BapFct_ENI2_FunctionList = 0x03,
  BapFct_ENI2_HeartBeat = 0x04,
  BapFct_ENI2_FSG_Control = 0x0d,
  BapFct_ENI2_FSG_Setup = 0x0e,
  BapFct_ENI2_FSG_OperationState = 0x0f,
  BapFct_ENI2_DestinationsList = 0x10,
  BapFct_ENI2_DestinationList_ASGcapacity = 0x11,
  BapFct_ENI2_TriggerRemoteProcess = 0x12,
  BapFct_ENI2_RemoteProcessCommands = 0x13,
  BapFct_ENI2_RemoteProcessState = 0x14,
  BapFct_ENI2_UserList = 0x15,
  BapFct_ENI2_ServiceList = 0x16,
  BapFct_ENI2_ActiveMonitorings = 0x17,
  BapFct_ENI2_PrivacySetup = 0x18,
  BapFct_ENI2_AlertList = 0x19,
  BapFct_ENI2_MobileDeviceKeyCount = 0x1a,
  BapFct_ENI2_VTANDataEncrypted = 0x1b,
  BapFct_ENI2_OnlineUpdateState_Deprecated = 0x1c,
  BapFct_ENI2_ConnectionState = 0x1d,
  BapFct_ENI2_ChallengeData = 0x1e,
  BapFct_ENI2_FoDList = 0x1f,
  BapFct_ENI2_FoDState = 0x20,
  BapFct_ENI2_ActiveTrip = 0x21,
  BapFct_ENI2_OLBSettings = 0x22,
  BapFct_ENI2_OLBTripList = 0x23,
  BapFct_ENI2_CurrentOnlineUpdateState = 0x24,
  BapFct_ENI2_OnlineUpdateList = 0x25,
  BapFct_ENI2_PrivacyGroupSetup = 0x26,
  BapFct_ENI2_FoD_M_FECList = 0x27,
  BapFct_ENI2_MobDevPairing = 0x28,
  BapFct_ENI2_OperationsList = 0x29,
  BapFct_ENI2_WlanState = 0x2a,
  BapFct_ENI2_WlanConfiguration = 0x2b,
  BapFct_ENI2_FoD_SyncState = 0x2c,
  BapFct_ENI2_FoD_BaseReportList = 0x2d,
  BapFct_ENI2_FoD_FunctionReportList = 0x2e,
  /* Steuergeraet EngineFunctions */
  BapFct_EngineFunctions_GetAll = 0x01,
  BapFct_EngineFunctions_BAP_Config = 0x02,
  BapFct_EngineFunctions_FunctionList = 0x03,
  BapFct_EngineFunctions_Heartbeat = 0x04,
  BapFct_EngineFunctions_FSG_Control = 0x0d,
  BapFct_EngineFunctions_FSG_Setup = 0x0e,
  BapFct_EngineFunctions_FSG_OperationState = 0x0f,
  BapFct_EngineFunctions_DoubleClutch = 0x10,
  BapFct_EngineFunctions_ISA_Enable = 0x11,
  BapFct_EngineFunctions_ISA_SpeedAdoptionMode = 0x12,
  BapFct_EngineFunctions_ISA_NoLimitSpeed = 0x13,
  BapFct_EngineFunctions_ISA_SpeedLimitOffset = 0x14,
  BapFct_EngineFunctions_Last_Trips_Data = 0x15,
  BapFct_EngineFunctions_Avr_Emission_Val = 0x16,
  BapFct_EngineFunctions_EEDWS_Status = 0x17,
  BapFct_EngineFunctions_OBFCM_Data = 0x18,
  BapFct_EngineFunctions_Avr_Emission_Val2 = 0x19,
  BapFct_EngineFunctions_Lifetime_Emissions = 0x1a,
  BapFct_EngineFunctions_OBM_Last_Trip = 0x1b,
  BapFct_EngineFunctions_ADAS_Operating_Config = 0x1c,
  BapFct_EngineFunctions_ADAS_TriggerOnButton = 0x1d,
  BapFct_EngineFunctions_ADAS_SpeedLimitAdopt = 0x1e,
  BapFct_EngineFunctions_ADAS_TravelSpeed = 0x1f,
  BapFct_EngineFunctions_pLimOffset = 0x20,
  BapFct_EngineFunctions_OBM_OBFCM_Live_Data = 0x21,
  /* Steuergeraet TPA */
  BapFct_TPA_GetAll = 0x01,
  BapFct_TPA_BAP_Config = 0x02,
  BapFct_TPA_FunctionList = 0x03,
  BapFct_TPA_Heartbeat = 0x04,
  BapFct_TPA_FSG_Control = 0x0d,
  BapFct_TPA_FSG_Setup = 0x0e,
  BapFct_TPA_FSG_OperationState = 0x0f,
  BapFct_TPA_ParkingSpace = 0x10,
  BapFct_TPA_Info = 0x11,
  BapFct_TPA_initScenario = 0x12,
  BapFct_TPA_saveDriveInTrajectory = 0x13,
  BapFct_TPA_saveDriveOutTrajectory = 0x14,
  BapFct_TPA_deleteTrajectory = 0x15,
  BapFct_TPA_teachInDriveOutTrajectory = 0x16,
  BapFct_TPA_remoteParking = 0x17,
  BapFct_TPA_Navigation = 0x18,
  BapFct_TPA_RemainingTrajLength = 0x19,
  BapFct_TPA_deleteDriveOutTrajectory = 0x1a,
  BapFct_TPA_TPA_Configuration = 0x1b,
  BapFct_TPA_teachInDriveInTrajectory = 0x1c,
  BapFct_TPA_RemainingTrajLength2 = 0x1d,
  /* Steuergeraet Car2X */
  BapFct_Car2X_GetAll = 0x01,
  BapFct_Car2X_BAP_Config = 0x02,
  BapFct_Car2X_FunctionList = 0x03,
  BapFct_Car2X_Heartbeat = 0x04,
  BapFct_Car2X_FSG_Control = 0x0d,
  BapFct_Car2X_FSG_Setup = 0x0e,
  BapFct_Car2X_FSG_OperationState = 0x0f,
  BapFct_Car2X_ObjectList_High = 0x10,
  BapFct_Car2X_ObjectList_Low = 0x11,
  BapFct_Car2X_PSO_ImExport = 0x12,
  BapFct_Car2X_Car2X_Control = 0x13,
  BapFct_Car2X_LGW_Control = 0x14,
  BapFct_Car2X_TLI_Control = 0x15,
  /* Steuergeraet IAA_PSO2 */
  BapFct_IAA_PSO2_GetAll = 0x01,
  BapFct_IAA_PSO2_BAP_Config = 0x02,
  BapFct_IAA_PSO2_FunctionList = 0x03,
  BapFct_IAA_PSO2_Heartbeat = 0x04,
  BapFct_IAA_PSO2_FSG_Control = 0x0d,
  BapFct_IAA_PSO2_FSG_OperationState = 0x0f,
  BapFct_IAA_PSO2_PSO_Prompt = 0x10,
  BapFct_IAA_PSO2_PSO_Control = 0x11,
  BapFct_IAA_PSO2_PSO_FSG_Setup = 0x12,
  BapFct_IAA_PSO2_IAA_ActiveUserAndProfile = 0x13,
  BapFct_IAA_PSO2_IAA_VehicleUserList = 0x14,
  BapFct_IAA_PSO2_IAA_TriggerRemoteProcess = 0x15,
  BapFct_IAA_PSO2_IAA_RemoteProcessCommands = 0x16,
  BapFct_IAA_PSO2_IAA_General_Status = 0x17,
  BapFct_IAA_PSO2_IAA_FFB_Key_Status = 0x18,
  BapFct_IAA_PSO2_IAA_ASG_Sync_Status = 0x19,
  BapFct_IAA_PSO2_N_Key_OV = 0x1a,
  BapFct_IAA_PSO2_N_Key_InCarMutualAuth = 0x1b,
  BapFct_IAA_PSO2_IAA_KeyReferenceList = 0x1c,
  BapFct_IAA_PSO2_IAA_TriggerLocalFunction = 0x1d,
  BapFct_IAA_PSO2_IAA_LocalFunctionCommands = 0x1e,
  BapFct_IAA_PSO2_RuR_PrimaryUser = 0x1f,
  BapFct_IAA_PSO2_IAA_FaceRec_Status = 0x20,
  /* Steuergeraet RollingAbility */
  BapFct_RollingAbility_GetAll = 0x01,
  BapFct_RollingAbility_BAP_Config = 0x02,
  BapFct_RollingAbility_FunctionList = 0x03,
  BapFct_RollingAbility_Heartbeat = 0x04,
  BapFct_RollingAbility_FSG_Control = 0x0d,
  BapFct_RollingAbility_FSG_Setup = 0x0e,
  BapFct_RollingAbility_FSG_OperationState = 0x0f,
  BapFct_RollingAbility_Display = 0x10,
  BapFct_RollingAbility_RASetup = 0x11,
  /* Steuergeraet BSMOIS */
  BapFct_BSMOIS_GetAll = 0x01,
  BapFct_BSMOIS_BAP_Config = 0x02,
  BapFct_BSMOIS_Functionlist = 0x03,
  BapFct_BSMOIS_Heartbeat = 0x04,
  BapFct_BSMOIS_FSG_Control = 0x0d,
  BapFct_BSMOIS_FSG_Setup = 0x0e,
  BapFct_BSMOIS_FSG_OperationState = 0x0f,
  BapFct_BSMOIS_SystemControl = 0x10,
  BapFct_BSMOIS_Brightness = 0x11,
  BapFct_BSMOIS_SoundControl = 0x12,
  BapFct_BSMOIS_SystemState = 0x13,
  /* Steuergeraet MobDevKey */
  BapFct_MobDevKey_GetAll = 0x01,
  BapFct_MobDevKey_BAP_Config = 0x02,
  BapFct_MobDevKey_FunctionList = 0x03,
  BapFct_MobDevKey_Heartbeat = 0x04,
  BapFct_MobDevKey_FSG_Control = 0x0d,
  BapFct_MobDevKey_FSG_Setup = 0x0e,
  BapFct_MobDevKey_FSG_OperationState = 0x0f,
  BapFct_MobDevKey_KeyList = 0x10,
  BapFct_MobDevKey_KeyExpirationConfirmation = 0x11,
  BapFct_MobDevKey_Settings = 0x12,
  BapFct_MobDevKey_MdkActivation = 0x13,
  BapFct_MobDevKey_InputSharingPassword = 0x14,
  BapFct_MobDevKey_TerminateKey = 0x15,
  BapFct_MobDevKey_PairOwner = 0x16,
  BapFct_MobDevKey_UnpairOwner = 0x17,
  BapFct_MobDevKey_ServiceCardActivation = 0x18,
  BapFct_MobDevKey_AuthorisedKey = 0x19,
  BapFct_MobDevKey_OwnerSharingControl = 0x1a,
  /* Steuergeraet BSMOIS2 */
  BapFct_BSMOIS2_GetAll = 0x01,
  BapFct_BSMOIS2_BAP_Config = 0x02,
  BapFct_BSMOIS2_Functionlist = 0x03,
  BapFct_BSMOIS2_Heartbeat = 0x04,
  BapFct_BSMOIS2_FSG_Control = 0x0d,
  BapFct_BSMOIS2_FSG_Setup = 0x0e,
  BapFct_BSMOIS2_FSG_OperationState = 0x0f,
  BapFct_BSMOIS2_SystemControl = 0x10,
  BapFct_BSMOIS2_Brightness = 0x11,
  BapFct_BSMOIS2_SoundControl = 0x12,
  BapFct_BSMOIS2_SystemState = 0x13,
  /* Steuergeraet BSMOIS3 */
  BapFct_BSMOIS3_GetAll = 0x01,
  BapFct_BSMOIS3_BAP_Config = 0x02,
  BapFct_BSMOIS3_Functionlist = 0x03,
  BapFct_BSMOIS3_Heartbeat = 0x04,
  BapFct_BSMOIS3_FSG_Control = 0x0d,
  BapFct_BSMOIS3_FSG_Setup = 0x0e,
  BapFct_BSMOIS3_FSG_OperationState = 0x0f,
  BapFct_BSMOIS3_SystemControl = 0x10,
  BapFct_BSMOIS3_Brightness = 0x11,
  BapFct_BSMOIS3_SoundControl = 0x12,
  BapFct_BSMOIS3_SystemState = 0x13,
  /* Steuergeraet RushhourPilot */
  BapFct_RushhourPilot_GetAll = 0x01,
  BapFct_RushhourPilot_BAP_Config = 0x02,
  BapFct_RushhourPilot_FunctionList = 0x03,
  BapFct_RushhourPilot_HeartBeat = 0x04,
  BapFct_RushhourPilot_FSG_Control = 0x0d,
  BapFct_RushhourPilot_FSG_Setup = 0x0e,
  BapFct_RushhourPilot_FSG_OperationState = 0x0f,
  BapFct_RushhourPilot_DriverTriggeredLC = 0x10,
  BapFct_RushhourPilot_DriverConfirmedLC = 0x11,
  BapFct_RushhourPilot_DistanceMode = 0x12,
  BapFct_RushhourPilot_DrivingMode = 0x13,
  BapFct_RushhourPilot_LaneFeature = 0x14,
  BapFct_RushhourPilot_DrivingAssist = 0x15,
  BapFct_RushhourPilot_NavigatedDriving = 0x16,
  BapFct_RushhourPilot_IntersectionAssistant = 0x17,
  BapFct_RushhourPilot_IPAFeature = 0x18,
  BapFct_RushhourPilot_TPAFeature = 0x19,
  BapFct_RushhourPilot_SummonFeature = 0x1a,
  BapFct_RushhourPilot_VoicePrompt = 0x1b,
  BapFct_RushhourPilot_FSG_Setup2 = 0x1c,
  BapFct_RushhourPilot_ParkListState = 0x1d,
  BapFct_RushhourPilot_ParkingDI = 0x1e,
  BapFct_RushhourPilot_RHP_Parkingslotstatus = 0x1f,
  BapFct_RushhourPilot_TPA_Messages = 0x20,
  BapFct_RushhourPilot_TPA_Destinationsharing = 0x21,
  BapFct_RushhourPilot_Parkingdirection = 0x22,
  BapFct_RushhourPilot_TPA_Guidestartpoint = 0x23,
  BapFct_RushhourPilot_SelfdefinePS = 0x24,
  BapFct_RushhourPilot_TPA_ParkingScenario = 0x25,
  BapFct_RushhourPilot_AVM_View = 0x26,
  BapFct_RushhourPilot_deleteScenario = 0x27,
  BapFct_RushhourPilot_saveScenario = 0x28,
  BapFct_RushhourPilot_Parking_Messages_CD = 0x29,
  /* Steuergeraet PlugAndCharge */
  BapFct_PlugAndCharge_GetAll = 0x01,
  BapFct_PlugAndCharge_BAP_Config = 0x02,
  BapFct_PlugAndCharge_FunctionList = 0x03,
  BapFct_PlugAndCharge_Heartbeat = 0x04,
  BapFct_PlugAndCharge_FSG_Control = 0x0d,
  BapFct_PlugAndCharge_FSG_Setup = 0x0e,
  BapFct_PlugAndCharge_FSG_OperationState = 0x0f,
  BapFct_PlugAndCharge_RootCaCertContainers = 0x10,
  BapFct_PlugAndCharge_UnknownRootCaCert = 0x11,
  BapFct_PlugAndCharge_VehicleCertificates = 0x12,
  BapFct_PlugAndCharge_Contracts = 0x13,
  BapFct_PlugAndCharge_Status = 0x14,
  BapFct_PlugAndCharge_PrimaryUser = 0x15,
  /* Steuergeraet California */
  BapFct_California_GetAll = 0x01,
  BapFct_California_BAP_Config = 0x02,
  BapFct_California_FunctionList = 0x03,
  BapFct_California_Heartbeat = 0x04,
  BapFct_California_FSG_Control = 0x0d,
  BapFct_California_FSG_Setup = 0x0e,
  BapFct_California_FSG_OperationState = 0x0f,
  BapFct_California_Wastewater = 0x10,
  BapFct_California_Popup_roof = 0x11,
  BapFct_California_Bluetooth = 0x12,
  BapFct_California_Campermodus = 0x13,
  BapFct_California_Energy = 0x14,
  BapFct_California_Fresh_Water = 0x15,
  BapFct_California_Cooling_Box = 0x16,
  BapFct_California_Tilt_Indicator = 0x17,
  BapFct_California_AirHeater = 0x18,
  BapFct_California_FSG_Setup2 = 0x19,
  BapFct_California_Freshwater2 = 0x1a,
  BapFct_California_Stairs = 0x1b,
  BapFct_California_SatelliteSystem = 0x1c,
  BapFct_California_RooftopAirConditioning = 0x1d,
  BapFct_California_AirHeater_WaterHeater = 0x1e,
  BapFct_California_FSG_Setup3 = 0x1f,
  BapFct_California_OutputParams = 0x20,
  BapFct_California_InputParams = 0x21,
  BapFct_California_ActiveTimer = 0x22,
  BapFct_California_Timer1 = 0x23,
  BapFct_California_Lights = 0x24,
  BapFct_California_Profiles = 0x25,
  BapFct_California_Colour = 0x26,
  BapFct_California_SpecialProfiles = 0x27,
  BapFct_California_DoorContact = 0x28,
  BapFct_California_FSG_Setup4 = 0x29,
  BapFct_California_OutputParams2 = 0x2a,
  BapFct_California_InputParams2 = 0x2b,
  BapFct_California_OutputParams3 = 0x2c,
  BapFct_California_InputParams3 = 0x2d,
  BapFct_California_OutputParams4 = 0x2e,
  BapFct_California_InputParams4 = 0x2f,
  BapFct_California_EPTO_Activation = 0x30,
  BapFct_California_EPTO_StatusInfo = 0x31,
  BapFct_California_EPTO_Statistics = 0x32,
  BapFct_California_EPTO_ShutDownSoc = 0x33,
  BapFct_California_EPTO_StartTimer = 0x34,
  BapFct_California_EPTO_StopTimer = 0x35,
  BapFct_California_EPTO_Messages = 0x36,
  BapFct_California_EPTO_Views = 0x37,
  BapFct_California_NightSetback = 0x38,
  /* Steuergeraet SLCView */
  BapFct_SLCView_GetAll = 0x01,
  BapFct_SLCView_BAP_Config = 0x02,
  BapFct_SLCView_FunctionList = 0x03,
  BapFct_SLCView_Heartbeat = 0x04,
  BapFct_SLCView_FSG_Control = 0x0d,
  BapFct_SLCView_FSG_Setup = 0x0e,
  BapFct_SLCView_FSG_OperationState = 0x0f,
  BapFct_SLCView_SystemState = 0x10,
  BapFct_SLCView_ViewRequest_HU = 0x11,
  BapFct_SLCView_ViewRequest_IC = 0x12,
  BapFct_SLCView_ViewState_HU = 0x13,
  BapFct_SLCView_ViewState_IC = 0x14,
  BapFct_SLCView_IC_Messages = 0x15,
  BapFct_SLCView_HU_Messages = 0x16,
  BapFct_SLCView_FeatureState = 0x17
}fctId_t;

#endif
#ifdef __cplusplus
}
#endif

#endif      /* #ifndef BAP_DEFINES_H */
