#ifndef __CAN_FSG_TC__
#define __CAN_FSG_TC__

/* These define is manual and was not generated by Volkswagen tool */

/* --CAN-Rx-Handles-- */

#define BAP_Klima1_ASG_01               0
#define BAP_KlimaMaster_ASG_01          1

#define BAP_Klima1_FSG_01               100
#define BAP_KlimaMaster_FSG_01          101

#define BAP_Klima1_ASG_02               102
#define BAP_Klima1_ASG_03               103
#define BAP_Klima1_ASG_04               104
#define BAP_KlimaMaster_ASG_02          105
#define BAP_KlimaMaster_ASG_03          106
#define BAP_KlimaMaster_ASG_04          107

#endif // __CAN_FSG_TC__
