#ifndef __CAN_TC__
#define __CAN_TC__

/* These define is manual and was not generated by Volkswagen tool */

/* --CAN-Rx-Handles-- */

#define BAP_Klima1_ASG_01               0
#define BAP_KlimaMaster_ASG_01          1

#define BAP_Klima1_FSG_01               100
#define BAP_KlimaMaster_FSG_01          101

#endif // __CAN_TC__
